"""
D02_snr_vs_r2_simulation.py — SNR vs R² correlation for simulated data.

Loads the simulation timeseries generated by S01_simulate_prf.py,
computes SNR measures (from D01_analyze_snr.py approach), and correlates
them against pRF fit R² estimates from S02_run_simulation_fit.py.

Three SNR measures computed per voxel:
    1. Relative low-frequency power  — fraction of power in [f_min, f_max]
    2. tSNR                          — mean(signal) / std(signal)
    3. Mean squared amplitude (MSA)  — mean of squared detrended signal

Outputs saved to: figures/testing_snr/

Usage:
    python D02_snr_vs_r2_simulation.py [--grid-size Ns]
"""

import os
import sys
import pickle
import argparse

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from scipy import stats

from H01_config import DEFAULT_PARAMS, GRID_DEFAULTS, set_paths
from H03_fit_utils import remove_trend, set_dark_theme

# Frequency band for task-relevant power (same as D01)
F_MIN = 0.005
F_MAX = 0.08
TR    = 1.3   # seconds


def parse_args():
    parser = argparse.ArgumentParser(description='SNR vs R2 analysis for simulation data')
    parser.add_argument('--grid-size', type=int, default=GRID_DEFAULTS['Ns'],
                        help=f'Grid density Ns used in S02 (default: {GRID_DEFAULTS["Ns"]})')
    return parser.parse_args()


def compute_snr_measures(timeseries, tr=TR, f_min=F_MIN, f_max=F_MAX):
    """
    Compute three per-voxel SNR measures.

    Returns dict with keys:
        rel_low_freq_power, tsnr, msa
    """
    N, T = timeseries.shape

    # Normalise before FFT (same as D01)
    means = timeseries.mean(axis=1, keepdims=True)
    stds  = timeseries.std(axis=1, keepdims=True)
    stds[stds == 0] = 1.0
    ts_norm  = (timeseries - means) / stds

    data_fft = np.fft.rfft(ts_norm, axis=1)
    freqs    = np.fft.rfftfreq(T, d=tr)
    power    = np.abs(data_fft) ** 2

    task_mask  = (freqs >= f_min) & (freqs <= f_max)
    total_mask = freqs > 0

    denom = power[:, total_mask].sum(axis=1)
    denom[denom == 0] = 1.0
    rel_power = power[:, task_mask].sum(axis=1) / denom

    # tSNR: mean(raw) / std(raw)
    raw_mean = np.abs(means[:, 0])
    raw_std  = timeseries.std(axis=1)
    raw_std[raw_std == 0] = 1.0
    tsnr = raw_mean / raw_std

    # Mean squared amplitude of detrended signal
    msa = (timeseries ** 2).mean(axis=1)

    return dict(rel_low_freq_power=rel_power, tsnr=tsnr, msa=msa)


def _scatter_with_regression(ax, x, y, xlabel, ylabel, color, accent='#ff4081'):
    mask = np.isfinite(x) & np.isfinite(y)
    xs, ys = x[mask], y[mask]
    ax.scatter(xs, ys, s=4, alpha=0.35, color=color, edgecolors='none', rasterized=True)
    if len(xs) > 2:
        r, p = stats.pearsonr(xs, ys)
        m, b = np.polyfit(xs, ys, 1)
        xl = np.array([xs.min(), xs.max()])
        ax.plot(xl, m * xl + b, '--', color=accent, linewidth=1.4,
                label=f'r = {r:.3f}  (p={p:.2e})')
        ax.legend(fontsize=9, framealpha=0.25)
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    ax.grid(True, alpha=0.3)


def plot_per_measure(snr_measures, r2_vals, out_dir, tag):
    labels = {
        'rel_low_freq_power': f'Rel. Power [{F_MIN}\u2013{F_MAX} Hz]',
        'tsnr':               'Temporal SNR (tSNR)',
        'msa':                'Mean Squared Amplitude',
    }
    colors = {
        'rel_low_freq_power': '#ff9800',
        'tsnr':               '#76ff03',
        'msa':                '#e040fb',
    }
    for key, label in labels.items():
        snr = snr_measures[key]
        fig, axes = plt.subplots(1, 3, figsize=(18, 6))

        _scatter_with_regression(axes[0], snr, r2_vals, label, 'Model R\u00b2', colors[key])
        axes[0].set_title(f'{label} vs R\u00b2')

        axes[1].hist(snr[np.isfinite(snr)], bins=80,
                     color=colors[key], edgecolor='none', alpha=0.85)
        axes[1].set_xlabel(label)
        axes[1].set_ylabel('Count')
        axes[1].set_title(f'Distribution of {label}')
        axes[1].grid(True, alpha=0.3)

        axes[2].hist(r2_vals[np.isfinite(r2_vals)], bins=80,
                     color='#00e5ff', edgecolor='none', alpha=0.85)
        axes[2].set_xlabel('Model R\u00b2')
        axes[2].set_ylabel('Count')
        axes[2].set_title('Distribution of fitted R\u00b2')
        axes[2].grid(True, alpha=0.3)

        plt.tight_layout()
        fname = os.path.join(out_dir, f'{key}_vs_r2{tag}.png')
        plt.savefig(fname, dpi=200, bbox_inches='tight')
        plt.close(fig)
        print(f"  Saved: {fname}")


def plot_summary_panel(snr_measures, r2_vals, out_dir, tag):
    labels = {
        'rel_low_freq_power': f'Rel. Power [{F_MIN}\u2013{F_MAX} Hz]',
        'tsnr':               'tSNR',
        'msa':                'Mean Sq. Amplitude',
    }
    colors = ['#ff9800', '#76ff03', '#e040fb']
    fig, axs = plt.subplots(2, 3, figsize=(21, 12))

    for col, (key, label) in enumerate(labels.items()):
        snr = snr_measures[key]
        mask = np.isfinite(snr) & np.isfinite(r2_vals)
        xs, ys = snr[mask], r2_vals[mask]

        ax = axs[0, col]
        ax.scatter(xs, ys, s=4, alpha=0.3, color=colors[col],
                   edgecolors='none', rasterized=True)
        if len(xs) > 2:
            r, _ = stats.pearsonr(xs, ys)
            m, b = np.polyfit(xs, ys, 1)
            xl = np.array([xs.min(), xs.max()])
            ax.plot(xl, m * xl + b, '--', color='#ff4081', linewidth=1.5)
            ax.set_title(f'{label} vs R\u00b2  (r = {r:.3f})')
        ax.set_xlabel(label)
        ax.set_ylabel('Model R\u00b2')
        ax.grid(True, alpha=0.3)

        ax = axs[1, col]
        ax.hist(snr[np.isfinite(snr)], bins=80,
                color=colors[col], edgecolor='none', alpha=0.85)
        ax.set_xlabel(label)
        ax.set_ylabel('Count')
        ax.set_title(f'Distribution of {label}')
        ax.grid(True, alpha=0.3)

    plt.suptitle('SNR Measures vs pRF Fit R\u00b2 \u2014 Simulation', fontsize=16, y=1.01)
    plt.tight_layout()
    fname = os.path.join(out_dir, f'snr_summary_panel{tag}.png')
    plt.savefig(fname, dpi=200, bbox_inches='tight')
    plt.close(fig)
    print(f"  Saved: {fname}")


def main():
    args = parse_args()
    Ns   = args.grid_size

    params = dict(DEFAULT_PARAMS)
    params['subjID'] = 'JC'
    p, _ = set_paths(params['subjID'], data_format='volumetric')

    sim_dir     = os.path.join(p['pRF_data'], 'Simulation')
    sim_fit_dir = os.path.join(sim_dir, 'popeyeFit')
    fig_dir     = os.path.join(sim_dir, 'figures', 'testing_snr')
    os.makedirs(fig_dir, exist_ok=True)

    print(f"=== D02 SNR vs R2 Analysis (Ns={Ns}) ===")
    print(f"Output: {fig_dir}")

    # Load simulated timeseries
    voxels_path = os.path.join(sim_dir, 'simulatedVoxels.pkl')
    if not os.path.exists(voxels_path):
        print(f"ERROR: {voxels_path} not found. Run S01_simulate_prf.py first.")
        sys.exit(1)

    print("Loading simulated voxels...")
    with open(voxels_path, 'rb') as fh:
        scan_data = pickle.load(fh)
    print(f"  {scan_data.shape[0]:,} voxels x {scan_data.shape[1]} TRs")

    print("Detrending...")
    scan_detrended = remove_trend(scan_data, method='all')

    print("Computing SNR measures...")
    snr_measures = compute_snr_measures(scan_detrended, tr=TR)

    # Load R2 from final fit or fall back to grid fit
    ffit_path = os.path.join(sim_fit_dir, f'RF_ss5_fFit_popeye_Ns{Ns}.npy')
    gfit_path = os.path.join(sim_fit_dir, f'RF_ss5_gFit_popeye_Ns{Ns}.npy')

    if os.path.exists(ffit_path):
        print(f"Loading final-fit: {ffit_path}")
        fit_data  = np.load(ffit_path)
        tag       = f'_ffit_Ns{Ns}'
    elif os.path.exists(gfit_path):
        print(f"Final-fit not found; using grid-fit: {gfit_path}")
        fit_data  = np.load(gfit_path)
        tag       = f'_gfit_Ns{Ns}'
    else:
        print(f"ERROR: No fit files found for Ns={Ns} in {sim_fit_dir}")
        sys.exit(1)

    # CSS columns: theta r2 rho sigma n x y beta baseline
    r2_vals = fit_data[:, 1]
    n_fit   = fit_data.shape[0]
    if n_fit < scan_data.shape[0]:
        snr_measures = {k: v[:n_fit] for k, v in snr_measures.items()}

    print(f"  R2 — min={r2_vals.min():.3f}  max={r2_vals.max():.3f}  "
          f"mean={r2_vals.mean():.3f}")

    set_dark_theme()

    print("Plotting per-measure panels...")
    plot_per_measure(snr_measures, r2_vals, fig_dir, tag)

    print("Plotting summary panel...")
    plot_summary_panel(snr_measures, r2_vals, fig_dir, tag)

    print(f"\nDone. All figures in: {fig_dir}")


if __name__ == '__main__':
    main()
