"""
D02_snr_vs_r2_simulation.py
============================
Task-band Fractional Spectral Power vs pRF Fit R² — Simulation Validation

OVERVIEW
--------
This script tests whether a data-quality measure derived purely from the
raw fMRI timeseries can predict how well the pRF model fits a given voxel.
It computes "Task-band Fractional Spectral Power" (TFSP) per voxel, then
correlates that against R² from S02_run_simulation_fit.py.

MEASURE: Task-band Fractional Spectral Power (TFSP)
------------------------------------------------------
TFSP is a stimulus-aware extension of fALFF (Zou et al. 2008, Brain Research):

    TFSP = Σ |X(f)| for f in [f_min, f_max]
           ────────────────────────────────────
           Σ |X(f)| for all f > f_drift

where |X(f)| is the FFT amplitude at frequency f.

Key design decisions vs. naïve relative power:

  1. AMPLITUDE not power: We use |FFT|, not |FFT|², following the fALFF
     convention. Power (|FFT|²) over-weights large-amplitude frequency bins
     and is less robust to spectral spikes or physiological artifacts. The
     amplitude form gives a more uniform weighting across the spectrum.

  2. STIMULUS-DERIVED band [f_min, f_max]: The frequency band is not
     hardcoded to a resting-state convention (0.01–0.1 Hz). Instead, it is
     computed from the stimulus design — specifically the bar sweep cycle
     period, which sets the fundamental task frequency. The band spans from
     the Nyquist-limited fundamental down to its first harmonic, adapting
     automatically to any experiment design. For a typical bar sweep with
     cycle period ~25 s this resolves to roughly 0.008–0.08 Hz; for a fast
     event-related design the upper bound would shift higher.

  3. DRIFT FLOOR f_drift: Low-frequency scanner drift (< f_drift) is
     excluded from both numerator and denominator. This prevents drifty
     voxels from artificially inflating the measure. f_drift defaults to
     1 / (scan_duration / 2) — i.e., frequencies with periods longer than
     half the scan — but can be overridden.

WHY TFSP PREDICTS R² (SIMULATION CONTEXT)
------------------------------------------
In S01, voxels are generated by a deterministic CSS forward model (HRF
convolved with the stimulus response). The bar sweep signal concentrates
power in the low-frequency band matching the sweep periodicity. Additive
noise is broadband (white). Therefore:

    High signal amplitude → high TFSP → pRF model fits well → high R²

In real data the same logic holds: task-locked BOLD responses concentrate
energy in the task band; thermal, physiological, and motion noise are
broadband or at higher frequencies (cardiac ~1 Hz, respiratory ~0.3 Hz).

INPUTS
------
    Simulation/simulatedVoxels.pkl  — generated by S01_simulate_prf.py
    Simulation/popeyeFit/RF_ss5_[fg]Fit_popeye_Ns{Ns}.npy — from S02

OUTPUTS (saved to Simulation/figures/testing_snr/)
-------
    tfsp_vs_r2_{tag}.png           — scatter + regression + marginal hists
    tfsp_summary_panel_{tag}.png   — summary panel (scatter | TFSP hist | R2 hist)

USAGE
-----
    python D02_snr_vs_r2_simulation.py [--grid-size Ns]

    Examples:
        python D02_snr_vs_r2_simulation.py
        python D02_snr_vs_r2_simulation.py --grid-size 100
"""

import os
import sys
import pickle
import argparse

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from scipy import stats

from H01_config import DEFAULT_PARAMS, GRID_DEFAULTS, set_paths
from H03_fit_utils import remove_trend, set_dark_theme


# ─── Stimulus-aware band defaults ─────────────────────────────────────────────
# These approximate a bar-sweep pRF experiment. See compute_tfsp() docstring
# for how to make them stimulus-derived at runtime.
DEFAULT_SWEEP_PERIOD_S  = 25.0   # approximate bar sweep cycle period (seconds)
DEFAULT_TR              = 1.3    # seconds


def parse_args():
    parser = argparse.ArgumentParser(
        description='Task-band Fractional Spectral Power vs R² (simulation)')
    parser.add_argument('--grid-size', type=int, default=GRID_DEFAULTS['Ns'],
                        help=f'Grid density Ns used in S02 (default: {GRID_DEFAULTS["Ns"]})')
    parser.add_argument('--sweep-period', type=float, default=DEFAULT_SWEEP_PERIOD_S,
                        help='Bar sweep cycle period in seconds (used to set task band)')
    parser.add_argument('--tr', type=float, default=DEFAULT_TR,
                        help='Repetition time in seconds')
    return parser.parse_args()


# ─── Core computation ──────────────────────────────────────────────────────────

def compute_tfsp(timeseries, tr, sweep_period_s):
    """
    Compute Task-band Fractional Spectral Power (TFSP) per voxel.

    The task band is derived from the stimulus sweep period rather than
    fixed to a resting-state convention:

        f_fundamental = 1 / sweep_period_s        (lowest task frequency)
        f_max         = 4 * f_fundamental          (up to 4th harmonic)
        f_drift       = f_fundamental / 2          (below this → drift, excluded)

    Parameters
    ----------
    timeseries : ndarray, shape (N, T)
        Detrended voxel timeseries (N voxels, T timepoints).
    tr : float
        Repetition time in seconds.
    sweep_period_s : float
        Bar sweep cycle period in seconds. Sets the task frequency band.

    Returns
    -------
    tfsp : ndarray, shape (N,)
        Task-band Fractional Spectral Power per voxel, in [0, 1].
    f_min : float
        Lower edge of task band (Hz).
    f_max : float
        Upper edge of task band (Hz).
    f_drift : float
        Drift floor — frequencies below this are excluded (Hz).
    """
    N, T = timeseries.shape

    # Derive band from stimulus
    f_fundamental = 1.0 / sweep_period_s
    f_min         = f_fundamental                  # fundamental
    f_max         = 4.0 * f_fundamental            # up to 4th harmonic
    f_drift       = f_fundamental / 2.0            # exclude sub-fundamental drift

    # Clamp f_max to Nyquist
    f_nyquist = 0.5 / tr
    f_max = min(f_max, f_nyquist)

    # Normalise per voxel before FFT (removes amplitude differences across voxels
    # that would bias the ratio — same approach as fALFF in the literature)
    means = timeseries.mean(axis=1, keepdims=True)
    stds  = timeseries.std(axis=1,  keepdims=True)
    stds[stds == 0] = 1.0
    ts_norm = (timeseries - means) / stds

    # FFT amplitude spectrum
    data_fft = np.fft.rfft(ts_norm, axis=1)
    freqs    = np.fft.rfftfreq(T, d=tr)
    amp      = np.abs(data_fft)              # amplitude, not power

    # Masks
    task_mask  = (freqs >= f_min) & (freqs <= f_max)
    total_mask = freqs >  f_drift            # exclude DC and drift

    numerator   = amp[:, task_mask].sum(axis=1)
    denominator = amp[:, total_mask].sum(axis=1)
    denominator[denominator == 0] = 1.0

    tfsp = numerator / denominator

    return tfsp, f_min, f_max, f_drift


# ─── Plotting ──────────────────────────────────────────────────────────────────

def plot_tfsp_vs_r2(tfsp, r2_vals, f_min, f_max, f_drift, out_dir, tag):
    """
    Three-panel figure:
      Left  — scatter of TFSP vs R² with regression line and Pearson r
      Middle — histogram of TFSP values
      Right  — histogram of R² values
    """
    mask = np.isfinite(tfsp) & np.isfinite(r2_vals)
    xs, ys = tfsp[mask], r2_vals[mask]

    r, p = stats.pearsonr(xs, ys)
    rho, p_sp = stats.spearmanr(xs, ys)

    fig, axes = plt.subplots(1, 3, figsize=(21, 7))

    # ── Scatter ─────────────────────────────────────────────────────────────
    ax = axes[0]
    ax.scatter(xs, ys, s=4, alpha=0.35, color='#00e5ff', edgecolors='none',
               rasterized=True)
    if len(xs) > 2:
        m, b = np.polyfit(xs, ys, 1)
        xl = np.array([xs.min(), xs.max()])
        ax.plot(xl, m * xl + b, '--', color='#ff4081', linewidth=1.6)
    ax.set_xlabel(f'Task-band FSP  [{f_min:.3f} – {f_max:.3f} Hz]')
    ax.set_ylabel('Model R²')
    ax.set_title(
        f'TFSP vs R²\n'
        f'Pearson r = {r:.3f}  (p = {p:.2e})\n'
        f'Spearman ρ = {rho:.3f}  (p = {p_sp:.2e})'
    )
    ax.grid(True, alpha=0.3)

    # ── TFSP histogram ───────────────────────────────────────────────────────
    ax = axes[1]
    ax.hist(xs, bins=80, color='#ff9800', edgecolor='none', alpha=0.85)
    ax.axvline(np.median(xs), color='#ff4081', linestyle='--', linewidth=1.2,
               label=f'median = {np.median(xs):.3f}')
    ax.legend(fontsize=9, framealpha=0.3)
    ax.set_xlabel('Task-band Fractional Spectral Power')
    ax.set_ylabel('Count')
    ax.set_title(f'Distribution of TFSP\n(drift floor: f > {f_drift:.4f} Hz)')
    ax.grid(True, alpha=0.3)

    # ── R² histogram ────────────────────────────────────────────────────────
    ax = axes[2]
    ax.hist(ys, bins=80, color='#00e5ff', edgecolor='none', alpha=0.85)
    ax.axvline(np.median(ys), color='#ff4081', linestyle='--', linewidth=1.2,
               label=f'median = {np.median(ys):.3f}')
    ax.legend(fontsize=9, framealpha=0.3)
    ax.set_xlabel('Model R²')
    ax.set_ylabel('Count')
    ax.set_title('Distribution of fitted R²')
    ax.grid(True, alpha=0.3)

    plt.suptitle('Task-band Fractional Spectral Power vs pRF Model R²',
                 fontsize=14, y=1.02)
    plt.tight_layout()

    fname = os.path.join(out_dir, f'tfsp_vs_r2{tag}.png')
    plt.savefig(fname, dpi=200, bbox_inches='tight')
    plt.close(fig)
    print(f"  Saved: {fname}")


def plot_summary_panel(tfsp, r2_vals, f_min, f_max, f_drift, out_dir, tag):
    """
    2×2 summary: scatter | TFSP hist (top) | percentile profiles | R² hist (bottom).
    """
    mask = np.isfinite(tfsp) & np.isfinite(r2_vals)
    xs, ys = tfsp[mask], r2_vals[mask]
    r, p = stats.pearsonr(xs, ys)
    rho, _ = stats.spearmanr(xs, ys)

    fig, axs = plt.subplots(2, 2, figsize=(16, 12))

    # Top-left: scatter
    ax = axs[0, 0]
    ax.scatter(xs, ys, s=4, alpha=0.3, color='#00e5ff', edgecolors='none',
               rasterized=True)
    if len(xs) > 2:
        m, b = np.polyfit(xs, ys, 1)
        xl = np.array([xs.min(), xs.max()])
        ax.plot(xl, m * xl + b, '--', color='#ff4081', linewidth=1.5)
    ax.set_title(f'TFSP vs R²  (r = {r:.3f}, ρ = {rho:.3f})')
    ax.set_xlabel(f'TFSP  [{f_min:.3f}–{f_max:.3f} Hz]')
    ax.set_ylabel('Model R²')
    ax.grid(True, alpha=0.3)

    # Top-right: TFSP quantile breakdown of R²
    ax = axs[0, 1]
    n_q = 5
    edges = np.percentile(xs, np.linspace(0, 100, n_q + 1))
    q_means, q_stds, q_labels = [], [], []
    for i in range(n_q):
        lo, hi = edges[i], edges[i + 1]
        sel = ys[(xs >= lo) & (xs <= hi)]
        q_means.append(sel.mean())
        q_stds.append(sel.std())
        q_labels.append(f'Q{i+1}\n[{lo:.2f}–{hi:.2f}]')
    q_means = np.array(q_means)
    q_stds  = np.array(q_stds)
    xpos = np.arange(n_q)
    ax.bar(xpos, q_means, color='#00e5ff', alpha=0.8, edgecolor='none')
    ax.errorbar(xpos, q_means, yerr=q_stds, fmt='none',
                color='#ff4081', capsize=4, linewidth=1.5)
    ax.set_xticks(xpos)
    ax.set_xticklabels(q_labels, fontsize=8)
    ax.set_xlabel('TFSP Quintile')
    ax.set_ylabel('Mean R² ± std')
    ax.set_title('Mean R² by TFSP Quintile')
    ax.grid(True, axis='y', alpha=0.3)

    # Bottom-left: TFSP histogram
    ax = axs[1, 0]
    ax.hist(xs, bins=80, color='#ff9800', edgecolor='none', alpha=0.85)
    ax.axvline(np.median(xs), color='#ff4081', linestyle='--', linewidth=1.2,
               label=f'median={np.median(xs):.3f}')
    ax.legend(fontsize=9, framealpha=0.3)
    ax.set_xlabel('Task-band Fractional Spectral Power')
    ax.set_ylabel('Count')
    ax.set_title(f'TFSP Distribution  (drift floor > {f_drift:.4f} Hz)')
    ax.grid(True, alpha=0.3)

    # Bottom-right: R² histogram
    ax = axs[1, 1]
    ax.hist(ys, bins=80, color='#00e5ff', edgecolor='none', alpha=0.85)
    ax.axvline(np.median(ys), color='#ff4081', linestyle='--', linewidth=1.2,
               label=f'median={np.median(ys):.3f}')
    ax.legend(fontsize=9, framealpha=0.3)
    ax.set_xlabel('Model R²')
    ax.set_ylabel('Count')
    ax.set_title('R² Distribution from Fit')
    ax.grid(True, alpha=0.3)

    plt.suptitle('Task-band Fractional Spectral Power — Summary',
                 fontsize=15, y=1.01)
    plt.tight_layout()
    fname = os.path.join(out_dir, f'tfsp_summary_panel{tag}.png')
    plt.savefig(fname, dpi=200, bbox_inches='tight')
    plt.close(fig)
    print(f"  Saved: {fname}")


# ─── Main ──────────────────────────────────────────────────────────────────────

def main():
    args = parse_args()
    Ns   = args.grid_size
    tr   = args.tr
    sweep_period = args.sweep_period

    params = dict(DEFAULT_PARAMS)
    params['subjID'] = 'JC'
    p, _ = set_paths(params['subjID'], data_format='volumetric')

    sim_dir     = os.path.join(p['pRF_data'], 'Simulation')
    sim_fit_dir = os.path.join(sim_dir, 'popeyeFit')
    fig_dir     = os.path.join(sim_dir, 'figures', 'testing_snr')
    os.makedirs(fig_dir, exist_ok=True)

    print(f"=== D02 Task-band FSP vs R² (Ns={Ns}) ===")
    print(f"Output: {fig_dir}")
    print(f"TR={tr}s  |  Sweep period={sweep_period}s")

    # ── Load simulated timeseries ──────────────────────────────────────────
    voxels_path = os.path.join(sim_dir, 'simulatedVoxels.pkl')
    if not os.path.exists(voxels_path):
        print(f"ERROR: {voxels_path} not found. Run S01_simulate_prf.py first.")
        sys.exit(1)

    print("Loading simulated voxels...")
    with open(voxels_path, 'rb') as fh:
        scan_data = pickle.load(fh)
    print(f"  {scan_data.shape[0]:,} voxels  x  {scan_data.shape[1]} TRs")

    print("Detrending...")
    scan_detrended = remove_trend(scan_data, method='all')

    # ── Compute TFSP ──────────────────────────────────────────────────────
    print("Computing Task-band Fractional Spectral Power...")
    tfsp, f_min, f_max, f_drift = compute_tfsp(scan_detrended, tr, sweep_period)
    print(f"  Task band:   [{f_min:.4f}, {f_max:.4f}] Hz")
    print(f"  Drift floor:  f > {f_drift:.4f} Hz")
    print(f"  TFSP range:  [{tfsp.min():.3f}, {tfsp.max():.3f}]  "
          f"mean={tfsp.mean():.3f}  median={np.median(tfsp):.3f}")

    # ── Load R² from fit ──────────────────────────────────────────────────
    ffit_path = os.path.join(sim_fit_dir, f'RF_ss5_fFit_popeye_Ns{Ns}.npy')
    gfit_path = os.path.join(sim_fit_dir, f'RF_ss5_gFit_popeye_Ns{Ns}.npy')

    if os.path.exists(ffit_path):
        print(f"Loading final-fit estimates: {ffit_path}")
        fit_data = np.load(ffit_path)
        tag      = f'_ffit_Ns{Ns}'
    elif os.path.exists(gfit_path):
        print(f"Final-fit not found, using grid-fit: {gfit_path}")
        fit_data = np.load(gfit_path)
        tag      = f'_gfit_Ns{Ns}'
    else:
        print(f"ERROR: No fit files for Ns={Ns} in {sim_fit_dir}")
        print(f"Run:  python S02_run_simulation_fit.py --grid-size {Ns}")
        sys.exit(1)

    # CSS output columns: theta  r2  rho  sigma  n  x  y  beta  baseline
    r2_vals = fit_data[:, 1]
    n_fit   = fit_data.shape[0]

    if n_fit < scan_data.shape[0]:
        print(f"  Trimming TFSP to {n_fit:,} voxels (matching fit)")
        tfsp = tfsp[:n_fit]

    print(f"  R² range:    [{r2_vals.min():.3f}, {r2_vals.max():.3f}]  "
          f"mean={r2_vals.mean():.3f}")

    # ── Plot ──────────────────────────────────────────────────────────────
    set_dark_theme()

    print("Generating scatter + histogram panel...")
    plot_tfsp_vs_r2(tfsp, r2_vals, f_min, f_max, f_drift, fig_dir, tag)

    print("Generating summary panel...")
    plot_summary_panel(tfsp, r2_vals, f_min, f_max, f_drift, fig_dir, tag)

    print(f"\nDone. All figures saved to: {fig_dir}")


if __name__ == '__main__':
    main()
