"""
H03_fit_utils.py — Shared utility functions for the pRF fitting pipeline.

Contains:
    set_dark_theme()     — Apply consistent dark background style for matplotlib
    print_time()         — Formatted elapsed time printing
    remove_trend()       — Signal detrending and percent signal change
    constrain_grids()   — Eccentricity-based grid space pruning
    generate_bounds()    — Parameter bounds for optimization
    error_func()         — Objective function for scipy.optimize.minimize
"""

import warnings
import numpy as np
import jax.numpy as jnp
#from jax.experimental import checkify
import matplotlib.pyplot as plt
import sweepea.utilities as utils
from itertools import product
from scipy.signal import detrend


def set_dark_theme():
    """
    Apply a consistent dark theme for all matplotlib figures generated by the pipeline.
    Sets background to dark, high-contrast cyan/magenta/yellow accents, subtle grids.
    """
    plt.style.use('dark_background')
    plt.rcParams.update({
        'figure.facecolor': '#121212',
        'axes.facecolor': '#1e1e1e',
        'axes.edgecolor': '#444444',
        'axes.labelcolor': '#e0e0e0',
        'xtick.color': '#cccccc',
        'ytick.color': '#cccccc',
        'grid.color': '#333333',
        'grid.linestyle': '--',
        'grid.alpha': 0.5,
        'figure.titlesize': 14,
        'axes.titlesize': 12,
        'text.color': '#ffffff',
        'savefig.facecolor': '#121212',
        'savefig.edgecolor': 'none',
    })


def print_time(st_time, end_time, process_name):
    """Print elapsed time in a human-readable format."""
    duration = end_time - st_time
    if duration < 60:
        print(f'{process_name} took {round(duration, 2)} seconds')
    elif duration < 3600:
        print(f'{process_name} took {round(duration/60)} minutes '
              f'and {round(duration%60)} seconds')
    else:
        print(f'{process_name} took {round(duration//3600)} hours, '
              f'{round((duration%3600)//60)} minutes '
              f'and {round(duration%60)} seconds')


def remove_trend(signal, method='all'):
    """
    Detrend and normalize fMRI signal.

    Parameters
    ----------
    signal : ndarray
        Input signal array. Last axis is time.
    method : str
        'demean'             — subtract and divide by mean
        'prct_signal_change' — percent signal change (popeye utility)
        'all'                — linear detrend + percent signal change (default)

    Returns
    -------
    ndarray
        Processed signal.
    """
    if method == 'demean':
        return ((signal - np.mean(signal, axis=-1)[..., None])
                / np.mean(signal, axis=-1)[..., None])
    elif method == 'prct_signal_change':
        return utils.percent_change(signal, ax=-1)
    elif method == 'all':
        signal_mean = np.mean(signal, axis=-1)[..., None]
        signal_detrend = detrend(signal, axis=-1, type='linear') + signal_mean
        signal_pct = utils.percent_change(signal_detrend, ax=-1)
        return signal_pct
    else:
        raise ValueError(f"Unknown detrend method: '{method}'")

#adapted from vista rmSpaceSigmas.m
def linlogspace(start, stop, num, border, pctlin, reflect=False):
    """
    Generate spacing with linear section up to border, then log spacing after.
    
    Adapted from mrVista's rmSpaceSigmas.m. Linear spacing from `start` to 
    `border`, then log spacing from `border` to `stop`.
    
    Parameters
    ----------
    start : float
        Minimum value (minRF).
    stop : float
        Maximum value (maxRF).
    num : int
        Total number of points to generate.
    border : float
        Transition point between linear and log spacing.
    pctlin : float
        Percentage of points in the linear segment.
    reflect : bool
        Reflect the values about zero (i.e. values go from -stop:stop).
        Note: Will not give you the N you request w/ odd values of N or start==0, but you can do it if you want.
    
    Returns
    -------
    ndarray
        Spaced values from start to stop.
    """

    if reflect:
        assert (start>=0) and (stop>=0)
        if start==0:
            warnings.warn('Will return N-1 points if start==0 and reflect=True')
        if np.mod(num,2) == 1:
            warnings.warn('Will return N-1 points if N is odd and reflect=True.')
        num = num//2
    
    if stop <= border:
        # All linear if stop is within border
        return np.linspace(start, stop, num)

    # If border very close to stop, ignore pctlin
    r = border / stop
    r = max(r, pctlin)
    # Number of points in each section
    h1 = int(np.floor(num * r))       # linear points
    h2 = int(np.ceil(num * np.round(1 - r,decimals=3)))  # log points (round to handle floating point slop)
    assert h1+h2 == num
    
    # Linear section: start to border (exclude last point to avoid duplication)
    tmp = np.linspace(start, border, h1 + 1)
    s_lin = tmp[:-1]
    
    # Log section: border to stop
    s_log = np.geomspace(border, stop, h2)
    
    # Concatenate and return
    out = np.concatenate((s_lin, s_log))
    if not reflect:
        return out
    else:
        return np.sort(np.unique(np.concatenate((-out, out))))   

def _grid_axis_from_params(params):
    space = params['space']
    p = params.copy()
    del p['space']
    if space == 'lin':
        return np.linspace(**p)
    elif space=='log':
        return np.geomspace(**p)
    elif space=='linlog':
        return linlogspace(**p)
    else:
        raise ValueError('Unknkown grid spacing specified.')

def _set_param_minmax(grid_params,param, min_value=None, max_value=None):
    if min_value is not None:
        grid_params[param].update({'start':min_value})
    if max_value is not None:
        grid_params[param].update({'stop':max_value})

def _set_param_gridN(grid_params,N,param_list=('x','y','s')):
    for p in param_list:
        grid_params[p].update({'num': N})

def generate_grids(grid_params,constraint_func=None,*args):
    if isinstance(grid_params,dict):
        params = list(grid_params.values())
    else:
        params = grid_params.copy()

    grid_space_orig = np.array(list(product(*[_grid_axis_from_params(x) for x in params])), dtype=float)
    grid_space_orig = np.round(grid_space_orig,4)

    return grid_space_orig if constraint_func is None else constraint_func(grid_space_orig,*args)

    
def constrain_grids(grid_space_orig, stimulus):
    """
    Remove grid points that fall outside the stimulus field of view.

    Applies two eccentricity constraints:
        1. sqrt(x² + y²) < 2 * max_eccentricity
        2. sqrt(x² + y²) < max_eccentricity + 2 * sigma

    Parameters
    ----------
    grid_space_orig : list of tuple or ndarray
        Grid points as (x, y, sigma, n) tuples.
    stimulus : VisualStimulus
        Popeye stimulus object.

    Returns
    -------
    list of list
        Constrained grid points.
    """
    grid_space_orig = np.array(grid_space_orig)
    x, y, s = grid_space_orig[:, 0], grid_space_orig[:, 1], grid_space_orig[:, 2]
    distances = np.sqrt(x**2 + y**2)

    max_dist1 = 2 * stimulus.deg_x.max()
    max_dist2 = stimulus.deg_x.max() + 2 * s

    mask = (distances < max_dist1) & (distances < max_dist2)
    grid_space = grid_space_orig[mask]
    return grid_space #.tolist()


def generate_bounds(init_estim, param_width):
    """
    Generate parameter bounds for optimization based on grid estimate.

    Parameters
    ----------
    init_estim : array-like
        Initial estimate (9-element: theta, r2, rho, sigma, n, x, y, beta, baseline).
    param_width : list
        Search width for [x, y, sigma, n].

    Returns
    -------
    tuple of tuple
        Bounds for (x, y, sigma, n).
    """
    x_estim = init_estim[5]
    y_estim = init_estim[6]
    sigma_estim = init_estim[3]
    n_estim = init_estim[4]

    x_bounds = (x_estim - param_width[0], x_estim + param_width[0])
    y_bounds = (y_estim - param_width[1], y_estim + param_width[1])
    sigma_bounds = (sigma_estim - param_width[2], sigma_estim + param_width[2])
    n_bounds = (n_estim - param_width[3], n_estim + param_width[3])

    return (x_bounds, y_bounds, sigma_bounds, n_bounds)


def error_func_lsq(parameters, data, objective_function):
    """
    Error function for a least squares solver (full residual vector)

    Parameters
    ----------
    parameters : array-like
        Current (x, y, sigma, n) values.
    data : ndarray
        Observed timeseries.
    objective_function : callable
        Function that generates predicted timeseries from parameters.

    Returns
    -------
    float
        vector of residuals.
    """

    prediction = objective_function(parameters)

    #checkify.check(prediction.ndim==1, "foo!")

    #assert not np.any(np.isnan(prediction)), "%s" % parameters

    slope = jnp.dot(prediction, data) / prediction.shape[0]

    #penalty = jnp.minimum(0,jnp.sum(parameters[0:2]**2)-25**2)*100

    error = data - slope*prediction
    #error = jnp.append(data - slope*prediction,penalty)

    return error

def error_func_lsq_np(parameters, data, objective_function):
    """
    Error function for scipy.optimize.least_squares.

    Parameters
    ----------
    parameters : array-like
        Current (x, y, sigma, n) values.
    data : ndarray
        Observed timeseries.
    objective_function : callable
        Function that generates predicted timeseries from parameters.

    Returns
    -------
    float
        vector of residuals.
    """

    prediction = objective_function(parameters)

    #assert not np.any(np.isnan(prediction)), "%s" % parameters

    slope = np.dot(prediction,data)/len(prediction)

    error = data - slope*prediction

    return error


def error_func_min(parameters, data, objective_function):
    """
    Error function for general minimization objective (sum squared errors)

    Parameters
    ----------
    parameters : array-like
        Current (x, y, sigma, n) values.
    data : ndarray
        Observed timeseries.
    objective_function : callable
        Function that generates predicted timeseries from parameters.

    Returns
    -------
    float
        0.5 * sum(f_i(x)**2)
    """

    prediction = objective_function(parameters)

    #checkify.check(prediction.ndim==1, "foo!")

    #assert not np.any(np.isnan(prediction)), "%s" % parameters

    slope = jnp.dot(prediction, data) / prediction.shape[0]

    #penalty = jnp.minimum(0,jnp.sum(parameters[0:2]**2)-25**2)*100

    error = data - slope*prediction
    #error = jnp.append(data - slope*prediction,penalty)

    return 0.5 * jnp.dot(error,error)