"""
S02_run_simulation_fit.py — Run the pRF pipeline on simulated data and evaluate accuracy.

Loads synthetic data generated by S01_simulate_prf.py, runs the grid fit
and final fit, then plots fitted vs ground-truth parameters.

This consolidates the previously separate hpc_SimulationPredictor.py and
vader_SimulationPredictor.py into a single script.

Usage:
    python S02_run_simulation_fit.py
    python S02_run_simulation_fit.py --n-voxels 100 --use-gpu
    python S02_run_simulation_fit.py --grid-size 50 --skip-final-fit
"""

import argparse
import ctypes
import time
import os
import sys
import pickle
import traceback
from datetime import datetime

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import nibabel as nib

from itertools import product

import popeye.utilities_cclab as utils
from popeye.visual_stimulus import VisualStimulus

from H01_config import DEFAULT_PARAMS, GRID_DEFAULTS, set_paths, get_gridfit_path
from H02_dataloader import load_stimuli, save2nifti
from H03_fit_utils import print_time, remove_trend, constraint_grids, set_dark_theme
from H04_grid_predict import getGridPreds
from H05_grid_fit import get_grid_estims
from H06_final_fit import get_final_estims
from scipy import stats
from D01_analyze_snr import compute_tfsp


class TeeLogger:
    """
    Duplicates all writes to sys.stdout (and optionally sys.stderr) to a log file.
    Usage:
        logger = TeeLogger(log_path)
        sys.stdout = logger
        ...  # all print() calls go to both console and file
        logger.close()
    """

    def __init__(self, log_path):
        self._terminal = sys.__stdout__
        os.makedirs(os.path.dirname(log_path), exist_ok=True)
        self._log = open(log_path, 'w', buffering=1)  # line-buffered
        self.log_path = log_path

    def write(self, message):
        self._terminal.write(message)
        self._log.write(message)

    def flush(self):
        self._terminal.flush()
        self._log.flush()

    def close(self):
        sys.stdout = self._terminal
        sys.stderr = sys.__stderr__
        self._log.close()


def parse_args():
    parser = argparse.ArgumentParser(
        description='Run pRF fitting on simulated data and evaluate accuracy'
    )
    parser.add_argument('--n-voxels', type=int, default=None,
                        help='Number of voxels to test (default: all simulated voxels)')
    parser.add_argument('--grid-size', type=int, default=GRID_DEFAULTS['Ns'],
                        help=f'Grid density Ns (default: {GRID_DEFAULTS["Ns"]})')
    parser.add_argument('--use-gpu', action='store_true',
                        help='Enable GPU acceleration')
    parser.add_argument('--skip-final-fit', action='store_true',
                        help='Skip the final fit step')
    return parser.parse_args()


def load_simulation_data(p, nvox):
    """Load simulated voxels and ground-truth parameters."""
    sim_dir = os.path.join(p['pRF_data'], 'Simulation')

    with open(os.path.join(sim_dir, 'simulatedVoxels.pkl'), 'rb') as f:
        scan_data = pickle.load(f)

    with open(os.path.join(sim_dir, 'simulatedParams.pkl'), 'rb') as f:
        trueFitFile = pickle.load(f)
        trueFit_estims = np.asarray(trueFitFile['params_vox'])
        baseline_vox = trueFitFile['baseline_vox']

    # Convert ground truth from (x, y, sigma, n) to 9-element format
    # (theta, r2, rho, sigma, n, x, y, beta, baseline)
    trueFit_data = np.empty((trueFit_estims.shape[0], 9))
    trueFit_data[:, 0] = np.mod(np.arctan2(trueFit_estims[:, 1],
                                            trueFit_estims[:, 0]), 2 * np.pi)
    trueFit_data[:, 1] = 1  # Perfect R² for ground truth
    trueFit_data[:, 2] = np.sqrt(trueFit_estims[:, 0]**2 + trueFit_estims[:, 1]**2)
    trueFit_data[:, 3] = trueFit_estims[:, 2]
    trueFit_data[:, 4] = trueFit_estims[:, 3]
    trueFit_data[:, 5] = trueFit_estims[:, 0]
    trueFit_data[:, 6] = trueFit_estims[:, 1]
    trueFit_data[:, 7] = np.zeros(trueFit_estims.shape[0])
    trueFit_data[:, 8] = baseline_vox

    # Trim to requested number of voxels (or use all if nvox is None)
    if nvox is not None:
        scan_data = scan_data[:nvox, :]
        trueFit_data = trueFit_data[:nvox, :]

    return scan_data, trueFit_data


def plot_comparison(trueFit_data, fitted_data, title_prefix, save_path, tfsp=None):
    """
    Plot ground truth vs fitted parameters (dark theme).

    For spatial parameters (theta, rho, sigma, n, x, y): scatter of fitted vs ground truth.
    For R2 (idx 1): TFSP as a function of fitted R2 (if tfsp is provided).
    For beta (idx 7): histogram of fitted beta distribution.
    """
    param_names = ['theta', 'rsquared', 'rho', 'sigma', 'n', 'x', 'y', 'beta']

    f, axs = plt.subplots(2, 4, figsize=(20, 10))
    axs = axs.flatten()
    for i in range(8):
        ax = axs[i]
        fit_vals = fitted_data[:, i].flatten()

        if i == 1 and tfsp is not None:
            # TFSP as a function of R2
            ax.scatter(fit_vals, tfsp, s=8, alpha=0.4, color='#00e5ff', edgecolors='none')
            if len(fit_vals) > 2:
                r, p = stats.pearsonr(fit_vals, tfsp)
                m, b = np.polyfit(fit_vals, tfsp, 1)
                xl = np.array([fit_vals.min(), fit_vals.max()])
                ax.plot(xl, m * xl + b, '--', color='#ff4081', linewidth=1.2, label=f'r = {r:.3f}')
                ax.legend(fontsize=9, framealpha=0.3)
            ax.set_title(f"{title_prefix}: TFSP vs R2")
            ax.set_xlabel('Fitted R2')
            ax.set_ylabel('TFSP')
            ax.grid(True, alpha=0.3)
        elif i == 7:
            ax.hist(fit_vals, bins=60, color='#00e5ff', edgecolor='none', alpha=0.85)
            ax.set_title(f"{title_prefix}: {param_names[i]} (distribution)")
            ax.set_xlabel('Fitted value')
            ax.set_ylabel('Count')
            ax.grid(True, alpha=0.3)
        else:
            true_vals = trueFit_data[:, i].flatten()
            ax.scatter(true_vals, fit_vals, s=8, alpha=0.5,
                       color='#00e5ff', edgecolors='none')
            lims = [min(true_vals.min(), fit_vals.min()),
                    max(true_vals.max(), fit_vals.max())]
            ax.plot(lims, lims, '--', color='#ff4081', linewidth=1.2, label='identity')
            ax.set_xlim(lims)
            ax.set_ylim(lims)
            ax.set_title(f"{title_prefix}: {param_names[i]}")
            ax.set_xlabel('Ground Truth')
            ax.set_ylabel('Fitted')
            ax.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close(f)
    print(f"Comparison plot saved to {save_path}")


def plot_tfsp_binned_voxels(timeseries, tfsp, save_path, n_bins=5, n_cols=4):
    """Plot example detrended voxel timeseries grouped by TFSP (SNR) bin.

    Voxels are split into ``n_bins`` TFSP quantile bins; each bin is one row (top
    = low SNR → bottom = high SNR). The ``n_cols`` columns are example voxels
    spanning that bin's TFSP range (low→high within the bin). Replaces the old
    original-vs-detrended comparison.
    """
    tfsp = np.asarray(tfsp).flatten()
    edges = np.quantile(tfsp, np.linspace(0, 1, n_bins + 1))
    bin_labels = np.clip(np.digitize(tfsp, edges[1:-1]), 0, n_bins - 1)

    f, axs = plt.subplots(n_bins, n_cols, figsize=(4 * n_cols, 2.4 * n_bins),
                          squeeze=False)
    for b in range(n_bins):
        idx = np.where(bin_labels == b)[0]
        order = idx[np.argsort(tfsp[idx])] if idx.size else idx
        if order.size >= n_cols:
            sel = order[np.linspace(0, order.size - 1, n_cols).round().astype(int)]
        else:
            sel = order
        med = float(np.median(tfsp[idx])) if idx.size else np.nan
        for c in range(n_cols):
            ax = axs[b][c]
            if c < sel.size:
                v = int(sel[c])
                ax.plot(timeseries[v], color='#00e5ff', linewidth=1.0)
                ax.set_title(f'vox {v}  TFSP={tfsp[v]:.2f}', fontsize=8)
                ax.grid(True, alpha=0.3)
                if c == 0:
                    lbl = (f'bin {b}\nTFSP~{med:.2f}' if np.isfinite(med)
                           else f'bin {b}')
                    ax.set_ylabel(lbl, fontsize=9)
            else:
                ax.set_visible(False)
    f.suptitle('Detrended voxels by TFSP (SNR) bin '
               f'(top = low SNR → bottom = high SNR, {n_bins} bins)', fontsize=13)
    plt.tight_layout()
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close(f)
    print(f'TFSP-binned voxels plot saved to {save_path}')


def main():
    args = parse_args()
    codeStartTime = time.perf_counter()

    # Resolve paths first so log lands next to simulation results
    params = dict(DEFAULT_PARAMS)
    params['subjID'] = 'JC'
    p, _ = set_paths(params['subjID'], data_format='volumetric')

    # ── Logging setup ──────────────────────────────────────────────────────────
    log_dir = os.path.join(p['pRF_data'], 'Simulation', 'logs')
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    log_path = os.path.join(log_dir, f'S02_{timestamp}.log')
    logger = TeeLogger(log_path)
    sys.stdout = logger
    sys.stderr = logger  # capture tracebacks too
    # ───────────────────────────────────────────────────────────────────────────

    try:
        _run(args, codeStartTime, p, params)
    except Exception:
        traceback.print_exc()  # goes to log via stderr redirect
        raise
    finally:
        print(f'\nLog saved to: {log_path}')
        logger.close()


def _run(args, codeStartTime, p, params):
    # Apply dark theme globally for all figures in this run
    set_dark_theme()

    # Load simulation data
    print('Loading simulated data...')
    scan_data, trueFit_data = load_simulation_data(p, args.n_voxels)
    nvoxs = scan_data.shape[0]

    print(f'=== Simulation Validation Pipeline ===')
    print(f'Run started: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}')
    print(f'N voxels:  {nvoxs}')
    print(f'Grid size: {args.grid_size}')
    print(f'GPU:       {"enabled" if args.use_gpu else "disabled"}')
    print()

    # Detrend
    scan_data = remove_trend(scan_data, method='all')

    # TFSP (SNR) per voxel from the detrended data — used to bin the example
    # voxels below and, later, to color the fit-comparison plots.
    tfsp, _, _, _ = compute_tfsp(scan_data, tr=params['tr_length'], sweep_period_s=25.0)

    # Plot example detrended voxels grouped by TFSP (SNR) bin: 5 rows (bins,
    # low→high SNR) × 4 columns (example voxels spanning each bin).
    fig_dir = os.path.join(p['pRF_data'], 'Simulation', 'figures')
    os.makedirs(fig_dir, exist_ok=True)
    plot_tfsp_binned_voxels(scan_data, tfsp,
                            os.path.join(fig_dir, 'detrended_voxels.png'),
                            n_bins=5, n_cols=4)

    # Set up for volumetric-style fitting (1x1xN pseudo-volume)
    timeseries_data = scan_data
    indices = [(0, 0, i) for i in range(nvoxs)]
    print(f"Running model-fit on {nvoxs} voxels")

    # Load stimulus
    bar, _ = load_stimuli(p)
    bar = bar[:, :, 0:201]
    bar = np.flip(bar, axis=0)

    # Load NIfTI for affine/header (needed for saving)
    func_img = nib.load(p['pRF_ss5'])

    stimulus = VisualStimulus(
        bar.astype('int16'),
        params['viewingDistance'],
        params['screenWidth'],
        params['scaleFactor'],
        float(func_img.header['pixdim'][4]),
        params['dtype'],
    )

    # Build grid
    Ns = args.grid_size
    x_grid = np.concatenate((
        np.linspace(-stimulus.deg_x0.max(), stimulus.deg_x0.max(), Ns // 2),
        np.geomspace(-stimulus.deg_x0.max(), -2 * stimulus.deg_x0.max(), Ns // 4),
        np.geomspace(stimulus.deg_x0.max(), 2 * stimulus.deg_x0.max(), Ns // 4),
    ))
    y_grid = np.concatenate((
        np.linspace(-stimulus.deg_y0.max(), stimulus.deg_y0.max(), Ns // 2),
        np.geomspace(-stimulus.deg_y0.max(), -2 * stimulus.deg_y0.max(), Ns // 4),
        np.geomspace(stimulus.deg_y0.max(), 2 * stimulus.deg_y0.max(), Ns // 4),
    ))
    s_grid = np.concatenate((
        np.linspace(0.1, 5, 3 * Ns // 4),
        np.geomspace(5, stimulus.deg_x0.max(), Ns // 4),
    ))
    # Use the finer 10-value CSS-exponent grid (shared with S03) — the exponent
    # is the parameter most sensitive to grid resolution.
    n_grid = np.asarray(GRID_DEFAULTS['n_grid_values_fine'])
    grid_space_orig = list(product(x_grid, y_grid, s_grid, n_grid))
    grid_space = constraint_grids(grid_space_orig, stimulus)
    print(f'Grid space: {len(grid_space)} points '
          f'(n-grid resolution = {len(n_grid)})')

    param_width = [np.mean(np.diff(x_grid)), np.mean(np.diff(y_grid)),
                   np.mean(np.diff(s_grid)), np.mean(np.diff(n_grid))]

    # Grid predictions
    tstamp_start = time.perf_counter()
    gridfit_path = get_gridfit_path(p, Ns, n_res=len(n_grid))
    if os.path.exists(gridfit_path):
        print(f"Loading grid predictions from disk ({gridfit_path})")
        grid_preds = np.load(gridfit_path)
    else:
        print(f"Generating grid predictions ({gridfit_path})...")
        grid_preds = getGridPreds(grid_space, stimulus, gridfit_path,
                                  timeseries_data.shape[1])
    tstamp_gridpred = time.perf_counter()
    print_time(tstamp_start, tstamp_gridpred, 'Grid predictions')

    # Grid fit
    print('Starting grid fit...')
    RF_ss5_gFit = np.empty((1, 1, nvoxs, 9))
    RF_ss5_gFit = get_grid_estims(grid_preds, grid_space, timeseries_data,
                                   RF_ss5_gFit, indices, use_gpu=args.use_gpu)
    tstamp_gridfit = time.perf_counter()
    print_time(tstamp_gridpred, tstamp_gridfit, 'Grid fit')

    # Save and plot grid fit
    sim_fit_dir = os.path.join(p['pRF_data'], 'Simulation', 'popeyeFit')
    os.makedirs(sim_fit_dir, exist_ok=True)

    gfit_save_path = os.path.join(sim_fit_dir, f'RF_ss5_gFit_popeye_Ns{Ns}.npy')
    np.save(gfit_save_path, RF_ss5_gFit[0, 0, :, :])
    print(f"Grid-fit estimates saved to {gfit_save_path}")

    plot_comparison(trueFit_data, RF_ss5_gFit[0, 0, :, :],
                    f'Grid-fit (Ns={Ns})',
                    os.path.join(fig_dir, f'gridfit_comparison_Ns{Ns}.png'),
                    tfsp=tfsp)

    # Final fit (optional)
    if not args.skip_final_fit:
        print('Starting final fit...')
        RF_ss5_fFit = np.empty((1, 1, nvoxs, 9))
        RF_ss5_fFit = get_final_estims(RF_ss5_gFit, param_width, timeseries_data,
                                        stimulus, RF_ss5_fFit, indices,
                                        use_gpu=args.use_gpu)
        RF_ss5_fFit = RF_ss5_fFit.reshape(1, 1, nvoxs, 9)  # restore 4D shape
        tstamp_finalfit = time.perf_counter()
        print_time(tstamp_gridfit, tstamp_finalfit, 'Final fit')

        ffit_save_path = os.path.join(sim_fit_dir, f'RF_ss5_fFit_popeye_Ns{Ns}.npy')
        np.save(ffit_save_path, RF_ss5_fFit[0, 0, :, :])
        print(f"Final-fit estimates saved to {ffit_save_path}")

        plot_comparison(trueFit_data, RF_ss5_fFit[0, 0, :, :],
                        f'Final-fit (Ns={Ns})',
                        os.path.join(fig_dir, f'finalfit_comparison_Ns{Ns}.png'),
                        tfsp=tfsp)

    codeEndTime = time.perf_counter()
    print_time(codeStartTime, codeEndTime, 'Total simulation validation')


if __name__ == '__main__':
    main()
