"""
S02_run_simulation_fit.py — Run the pRF pipeline on simulated data and evaluate accuracy.

Loads synthetic data generated by S01_simulate_prf.py, runs the grid fit
and final fit, then plots fitted vs ground-truth parameters.

This consolidates the previously separate hpc_SimulationPredictor.py and
vader_SimulationPredictor.py into a single script.

Usage:
    python S02_run_simulation_fit.py
    python S02_run_simulation_fit.py --n-voxels 100 --use-gpu
    python S02_run_simulation_fit.py --grid-size 50 --skip-final-fit
"""

import argparse
import ctypes
import time
import os
import pickle

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import nibabel as nib

from itertools import product

import popeye.utilities_cclab as utils
from popeye.visual_stimulus import VisualStimulus

from H01_config import DEFAULT_PARAMS, GRID_DEFAULTS, set_paths
from H02_dataloader import load_stimuli, save2nifti
from H03_fit_utils import print_time, remove_trend, constraint_grids
from H04_grid_predict import getGridPreds
from H05_grid_fit import get_grid_estims
from H06_final_fit import get_final_estims


def parse_args():
    parser = argparse.ArgumentParser(
        description='Run pRF fitting on simulated data and evaluate accuracy'
    )
    parser.add_argument('--n-voxels', type=int, default=25,
                        help='Number of voxels to test (default: 25)')
    parser.add_argument('--grid-size', type=int, default=GRID_DEFAULTS['Ns'],
                        help=f'Grid density Ns (default: {GRID_DEFAULTS["Ns"]})')
    parser.add_argument('--use-gpu', action='store_true',
                        help='Enable GPU acceleration')
    parser.add_argument('--skip-final-fit', action='store_true',
                        help='Skip the final fit step')
    return parser.parse_args()


def load_simulation_data(p, nvox):
    """Load simulated voxels and ground-truth parameters."""
    sim_dir = os.path.join(p['pRF_data'], 'Simulation')

    with open(os.path.join(sim_dir, 'simulatedVoxels.pkl'), 'rb') as f:
        scan_data = pickle.load(f)

    with open(os.path.join(sim_dir, 'simulatedParams.pkl'), 'rb') as f:
        trueFitFile = pickle.load(f)
        trueFit_estims = np.asarray(trueFitFile['params_vox'])
        baseline_vox = trueFitFile['baseline_vox']

    # Convert ground truth from (x, y, sigma, n) to 9-element format
    # (theta, r2, rho, sigma, n, x, y, beta, baseline)
    trueFit_data = np.empty((trueFit_estims.shape[0], 9))
    trueFit_data[:, 0] = np.mod(np.arctan2(trueFit_estims[:, 1],
                                            trueFit_estims[:, 0]), 2 * np.pi)
    trueFit_data[:, 1] = 1  # Perfect R² for ground truth
    trueFit_data[:, 2] = np.sqrt(trueFit_estims[:, 0]**2 + trueFit_estims[:, 1]**2)
    trueFit_data[:, 3] = trueFit_estims[:, 2]
    trueFit_data[:, 4] = trueFit_estims[:, 3]
    trueFit_data[:, 5] = trueFit_estims[:, 0]
    trueFit_data[:, 6] = trueFit_estims[:, 1]
    trueFit_data[:, 7] = np.zeros(trueFit_estims.shape[0])
    trueFit_data[:, 8] = baseline_vox

    # Trim to requested number of voxels
    scan_data = scan_data[:nvox, :]
    trueFit_data = trueFit_data[:nvox, :]

    return scan_data, trueFit_data


def plot_comparison(trueFit_data, fitted_data, title_prefix, save_path):
    """Plot ground truth vs fitted parameters."""
    param_names = ['theta', 'rsquared', 'rho', 'sigma', 'n', 'x', 'y', 'beta']

    f, axs = plt.subplots(2, 4, figsize=(20, 10))
    axs = axs.flatten()
    for i in range(8):
        ax = axs[i]
        true_vals = trueFit_data[:, i].flatten()
        fit_vals = fitted_data[:, i].flatten()
        ax.plot(true_vals, fit_vals, 'o', markersize=4, alpha=0.7)
        ax.plot(ax.get_xlim(), ax.get_xlim(), 'k--')
        ax.set_title(f"{title_prefix}: {param_names[i]}")
        ax.set_xlabel('Ground Truth')
        ax.set_ylabel('Fitted')

    plt.tight_layout()
    plt.savefig(save_path, dpi=300)
    plt.close(f)
    print(f"Comparison plot saved to {save_path}")


def main():
    args = parse_args()
    codeStartTime = time.perf_counter()

    print(f'=== Simulation Validation Pipeline ===')
    print(f'N voxels:  {args.n_voxels}')
    print(f'Grid size: {args.grid_size}')
    print(f'GPU:       {"enabled" if args.use_gpu else "disabled"}')
    print()

    # Set paths (use a dummy subject for stimulus paths)
    params = dict(DEFAULT_PARAMS)
    params['subjID'] = 'JC'
    p, _ = set_paths(params['subjID'], data_format='volumetric')

    # Load simulation data
    print('Loading simulated data...')
    scan_data, trueFit_data = load_simulation_data(p, args.n_voxels)
    nvoxs = scan_data.shape[0]

    # Detrend
    scan_data_orig = scan_data.copy()
    scan_data = remove_trend(scan_data, method='all')

    # Plot detrending example
    fig_dir = os.path.join(p['pRF_data'], 'Simulation', 'figures')
    os.makedirs(fig_dir, exist_ok=True)

    f, axs = plt.subplots(2, 5, figsize=(20, 10))
    for i in range(min(5, nvoxs)):
        axs[0, i].plot(scan_data_orig[i])
        axs[0, i].set_title('Original')
        axs[1, i].plot(scan_data[i])
        axs[1, i].set_title('Detrended')
    plt.tight_layout()
    plt.savefig(os.path.join(fig_dir, 'detrended_voxels.png'), dpi=300)
    plt.close(f)

    # Set up for volumetric-style fitting (1x1xN pseudo-volume)
    timeseries_data = scan_data
    indices = [(0, 0, i) for i in range(nvoxs)]
    print(f"Running model-fit on {nvoxs} voxels")

    # Load stimulus
    bar, _ = load_stimuli(p)
    bar = bar[:, :, 0:201]
    bar = np.flip(bar, axis=0)

    # Load NIfTI for affine/header (needed for saving)
    func_img = nib.load(p['pRF_ss5'])

    stimulus = VisualStimulus(
        bar.astype('int16'),
        params['viewingDistance'],
        params['screenWidth'],
        params['scaleFactor'],
        float(func_img.header['pixdim'][4]),
        params['dtype'],
    )

    # Build grid
    Ns = args.grid_size
    x_grid = np.concatenate((
        np.linspace(-stimulus.deg_x0.max(), stimulus.deg_x0.max(), Ns // 2),
        np.geomspace(-stimulus.deg_x0.max(), -2 * stimulus.deg_x0.max(), Ns // 4),
        np.geomspace(stimulus.deg_x0.max(), 2 * stimulus.deg_x0.max(), Ns // 4),
    ))
    y_grid = np.concatenate((
        np.linspace(-stimulus.deg_y0.max(), stimulus.deg_y0.max(), Ns // 2),
        np.geomspace(-stimulus.deg_y0.max(), -2 * stimulus.deg_y0.max(), Ns // 4),
        np.geomspace(stimulus.deg_y0.max(), 2 * stimulus.deg_y0.max(), Ns // 4),
    ))
    s_grid = np.concatenate((
        np.linspace(0.1, 5, 3 * Ns // 4),
        np.geomspace(5, stimulus.deg_x0.max(), Ns // 4),
    ))
    n_grid = np.asarray(GRID_DEFAULTS['n_grid_values'])
    grid_space_orig = list(product(x_grid, y_grid, s_grid, n_grid))
    grid_space = constraint_grids(grid_space_orig, stimulus)
    print(f'Grid space: {len(grid_space)} points')

    param_width = [np.mean(np.diff(x_grid)), np.mean(np.diff(y_grid)),
                   np.mean(np.diff(s_grid)), np.mean(np.diff(n_grid))]

    # Grid predictions
    tstamp_start = time.perf_counter()
    gridfit_path = p['gridfit_path']
    if os.path.exists(gridfit_path):
        print("Loading grid predictions from disk")
        grid_preds = np.load(gridfit_path)
    else:
        print("Generating grid predictions...")
        grid_preds = getGridPreds(grid_space, stimulus, gridfit_path,
                                  timeseries_data.shape[1])
    tstamp_gridpred = time.perf_counter()
    print_time(tstamp_start, tstamp_gridpred, 'Grid predictions')

    # Grid fit
    print('Starting grid fit...')
    RF_ss5_gFit = np.empty((1, 1, nvoxs, 9))
    RF_ss5_gFit = get_grid_estims(grid_preds, grid_space, timeseries_data,
                                   RF_ss5_gFit, indices, use_gpu=args.use_gpu)
    tstamp_gridfit = time.perf_counter()
    print_time(tstamp_gridpred, tstamp_gridfit, 'Grid fit')

    # Save and plot grid fit
    sim_fit_dir = os.path.join(p['pRF_data'], 'Simulation', 'popeyeFit')
    os.makedirs(sim_fit_dir, exist_ok=True)
    save2nifti(RF_ss5_gFit,
               os.path.join(sim_fit_dir, 'RF_ss5_gFit_popeye.nii.gz'),
               func_img.affine, func_img.header)

    plot_comparison(trueFit_data, RF_ss5_gFit[0, 0, :, :],
                    'Grid-fit',
                    os.path.join(fig_dir, 'gridfit_comparison.png'))

    # Final fit (optional)
    if not args.skip_final_fit:
        print('Starting final fit...')
        RF_ss5_fFit = np.empty((1, 1, nvoxs, 9))
        RF_ss5_fFit = get_final_estims(RF_ss5_gFit, param_width, timeseries_data,
                                        stimulus, RF_ss5_fFit, indices,
                                        use_gpu=args.use_gpu)
        tstamp_finalfit = time.perf_counter()
        print_time(tstamp_gridfit, tstamp_finalfit, 'Final fit')

        save2nifti(RF_ss5_fFit,
                   os.path.join(sim_fit_dir, 'RF_ss5_fFit_popeye.nii.gz'),
                   func_img.affine, func_img.header)

        plot_comparison(trueFit_data, RF_ss5_fFit[0, 0, :, :],
                        'Final-fit',
                        os.path.join(fig_dir, 'finalfit_comparison.png'))

    codeEndTime = time.perf_counter()
    print_time(codeStartTime, codeEndTime, 'Total simulation validation')


if __name__ == '__main__':
    main()
