"""
S03_gridsize_sweep.py — Sweep grid density (Ns) on simulated data to find the optimal grid size.

Loads the synthetic data generated by S01_simulate_prf.py and, for each Ns in a
sweep, runs the full grid fit + final fit and records how well each parameter is
recovered relative to ground truth. Produces "accuracy vs Ns" and "runtime vs Ns"
summary figures — the two sides of the grid-density cost/benefit tradeoff.

Differences from S02_run_simulation_fit.py:
  * Loops over many Ns values (default: 10, 20, ..., 100) in one process.
  * Uses a finer CSS exponent (n) grid — 10 values instead of the default 4 —
    since the exponent is the parameter most sensitive to grid resolution.
  * GPU is the default (pass --no-gpu to disable).
  * Grid predictions are cached under an S03-specific name that also encodes the
    n-grid resolution, so they never collide with S02's `gridfit_{Ns}.npy` caches
    (the grid spaces differ).

Usage:
    python S03_gridsize_sweep.py
    python S03_gridsize_sweep.py --grid-sizes 10 20 30 40 50 60 70 80 90 100
    python S03_gridsize_sweep.py --n-voxels 5000 --no-gpu
"""

import argparse
import time
import os
import sys
import traceback
from datetime import datetime

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import nibabel as nib

from itertools import product
from scipy import stats

from popeye.visual_stimulus import VisualStimulus

from H01_config import DEFAULT_PARAMS, set_paths
from H02_dataloader import load_stimuli
from H03_fit_utils import print_time, remove_trend, constraint_grids, set_dark_theme
from H04_grid_predict import getGridPreds
from H05_grid_fit import get_grid_estims
from H06_final_fit import get_final_estims

# Reuse S02's simulation loader and tee logger to avoid duplication.
from S02_run_simulation_fit import TeeLogger, load_simulation_data


# Finer CSS exponent grid for the sweep (10 values vs the default 4).
N_GRID_VALUES = np.round(np.linspace(0.25, 1.0, 10), 4).tolist()

# Parameters plotted as identity scatters in S02 (i.e. those with a meaningful
# ground truth to correlate against). Index into the 9-element CSS estimate.
CORR_PARAMS = [
    ('theta', 0),
    ('rho', 2),
    ('sigma', 3),
    ('n', 4),
    ('x', 5),
    ('y', 6),
]


def parse_args():
    parser = argparse.ArgumentParser(
        description='Sweep grid density (Ns) on simulated data and evaluate accuracy vs runtime'
    )
    parser.add_argument('--grid-sizes', type=int, nargs='+',
                        default=[10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
                        help='Grid densities Ns to sweep (default: 10..100 by 10)')
    parser.add_argument('--n-voxels', type=int, default=None,
                        help='Number of voxels to test (default: all simulated voxels)')
    parser.add_argument('--no-gpu', dest='use_gpu', action='store_false',
                        help='Disable GPU acceleration (GPU is used by default)')
    parser.add_argument('--skip-final-fit', action='store_true',
                        help='Run coarse grid fit only; skip the final fit step')
    parser.add_argument('--n-iter', type=int, default=300,
                        help='Adam iterations per sub-batch in the GPU final fit (default: 300)')
    parser.add_argument('--lr', type=float, default=0.005,
                        help='Adam learning rate for the GPU final fit (default: 0.005)')
    parser.add_argument('--sub-batch', type=int, default=None,
                        help='Voxels per GPU sub-batch (default: auto-size from free VRAM)')
    parser.set_defaults(use_gpu=True)
    return parser.parse_args()


def get_s03_gridfit_path(p, Ns, n_res):
    """S03-specific grid-prediction cache path (encodes Ns and n-grid resolution)."""
    return os.path.join(p['stimuli_path'], f'gridfit_S03_Ns{Ns}_n{n_res}.npy')


def build_grid_space(stimulus, Ns):
    """Build the (x, y, sigma, n) grid space for a given Ns, using the fine n grid.

    Mirrors the grid construction in S02 but substitutes the 10-point n grid.
    Returns (grid_space, param_width).
    """
    x_grid = np.concatenate((
        np.linspace(-stimulus.deg_x0.max(), stimulus.deg_x0.max(), Ns // 2),
        np.geomspace(-stimulus.deg_x0.max(), -2 * stimulus.deg_x0.max(), Ns // 4),
        np.geomspace(stimulus.deg_x0.max(), 2 * stimulus.deg_x0.max(), Ns // 4),
    ))
    y_grid = np.concatenate((
        np.linspace(-stimulus.deg_y0.max(), stimulus.deg_y0.max(), Ns // 2),
        np.geomspace(-stimulus.deg_y0.max(), -2 * stimulus.deg_y0.max(), Ns // 4),
        np.geomspace(stimulus.deg_y0.max(), 2 * stimulus.deg_y0.max(), Ns // 4),
    ))
    s_grid = np.concatenate((
        np.linspace(0.1, 5, 3 * Ns // 4),
        np.geomspace(5, stimulus.deg_x0.max(), Ns // 4),
    ))
    n_grid = np.asarray(N_GRID_VALUES)

    grid_space_orig = list(product(x_grid, y_grid, s_grid, n_grid))
    grid_space = constraint_grids(grid_space_orig, stimulus)

    param_width = [np.mean(np.diff(x_grid)), np.mean(np.diff(y_grid)),
                   np.mean(np.diff(s_grid)), np.mean(np.diff(n_grid))]
    return grid_space, param_width


def safe_pearsonr(true_vals, fit_vals):
    """Pearson r over finite pairs; NaN if too few or degenerate."""
    true_vals = np.asarray(true_vals, dtype=float).flatten()
    fit_vals = np.asarray(fit_vals, dtype=float).flatten()
    mask = np.isfinite(true_vals) & np.isfinite(fit_vals)
    if mask.sum() < 3:
        return np.nan
    tv, fv = true_vals[mask], fit_vals[mask]
    if np.std(tv) == 0 or np.std(fv) == 0:
        return np.nan
    return stats.pearsonr(tv, fv)[0]


def compute_metrics(trueFit_data, fitted_data):
    """Return (dict of param->Pearson r vs ground truth, mean R²)."""
    corr = {name: safe_pearsonr(trueFit_data[:, idx], fitted_data[:, idx])
            for name, idx in CORR_PARAMS}
    mean_r2 = float(np.nanmean(fitted_data[:, 1]))
    return corr, mean_r2


def fit_one_gridsize(Ns, stimulus, timeseries_data, indices, nvoxs, p, use_gpu,
                     skip_final_fit, n_iter=300, lr=0.005, sub_batch=None):
    """Run grid (+ optional final) fit for a single Ns. Returns a results dict."""
    print(f'\n{"="*70}\n=== Ns = {Ns} ===\n{"="*70}')

    grid_space, param_width = build_grid_space(stimulus, Ns)
    print(f'Grid space: {len(grid_space)} points '
          f'(n-grid resolution = {len(N_GRID_VALUES)})')

    # Grid predictions (cached per Ns + n-resolution).
    t0 = time.perf_counter()
    gridfit_path = get_s03_gridfit_path(p, Ns, len(N_GRID_VALUES))
    if os.path.exists(gridfit_path):
        print(f'Loading grid predictions from disk ({gridfit_path})')
        grid_preds = np.load(gridfit_path)
    else:
        print(f'Generating grid predictions ({gridfit_path})...')
        grid_preds = getGridPreds(grid_space, stimulus, gridfit_path,
                                  timeseries_data.shape[1])
    t_pred = time.perf_counter()
    print_time(t0, t_pred, f'[Ns={Ns}] Grid predictions')

    # Grid fit.
    print('Starting grid fit...')
    RF_gFit = np.empty((1, 1, nvoxs, 9))
    RF_gFit = get_grid_estims(grid_preds, grid_space, timeseries_data,
                              RF_gFit, indices, use_gpu=use_gpu)
    t_grid = time.perf_counter()
    grid_time = t_grid - t_pred
    print_time(t_pred, t_grid, f'[Ns={Ns}] Grid fit')

    result = {
        'Ns': Ns,
        'n_grid_points': len(grid_space),
        'grid_fit_time': grid_time,
        'grid': None,
        'final': None,
    }
    grid_corr, grid_r2 = compute_metrics(trueFit_data_global, RF_gFit[0, 0, :, :])
    result['grid'] = {'corr': grid_corr, 'mean_r2': grid_r2}

    # Final fit (optional).
    if not skip_final_fit:
        print('Starting final fit...')
        RF_fFit = np.empty((1, 1, nvoxs, 9))
        RF_fFit = get_final_estims(RF_gFit, param_width, timeseries_data,
                                   stimulus, RF_fFit, indices, use_gpu=use_gpu,
                                   n_iter=n_iter, lr=lr, sub_batch=sub_batch)
        RF_fFit = RF_fFit.reshape(1, 1, nvoxs, 9)
        t_final = time.perf_counter()
        result['final_fit_time'] = t_final - t_grid
        print_time(t_grid, t_final, f'[Ns={Ns}] Final fit')

        final_corr, final_r2 = compute_metrics(trueFit_data_global, RF_fFit[0, 0, :, :])
        result['final'] = {'corr': final_corr, 'mean_r2': final_r2}
    else:
        result['final_fit_time'] = np.nan

    return result


def plot_accuracy_vs_ns(results, save_path, skip_final_fit):
    """One panel per correlated parameter: Pearson r vs Ns (grid & final)."""
    Ns_vals = [r['Ns'] for r in results]

    f, axs = plt.subplots(2, 3, figsize=(18, 10))
    axs = axs.flatten()
    for ax, (name, _) in zip(axs, CORR_PARAMS):
        grid_r = [r['grid']['corr'][name] for r in results]
        ax.plot(Ns_vals, grid_r, '-o', color='#00e5ff', linewidth=1.6,
                markersize=5, label='grid fit')
        if not skip_final_fit:
            final_r = [r['final']['corr'][name] for r in results]
            ax.plot(Ns_vals, final_r, '-s', color='#ff4081', linewidth=1.6,
                    markersize=5, label='final fit')
        ax.set_title(f'{name}: corr(fitted, ground truth) vs Ns')
        ax.set_xlabel('Grid size (Ns)')
        ax.set_ylabel('Pearson r')
        ax.grid(True, alpha=0.3)
        ax.legend(fontsize=9, framealpha=0.3)

    f.suptitle('Parameter recovery vs grid size', fontsize=15)
    plt.tight_layout()
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close(f)
    print(f'Accuracy-vs-Ns plot saved to {save_path}')


def plot_r2_vs_ns(results, save_path, skip_final_fit):
    """Mean fitted R² as a function of Ns (grid & final)."""
    Ns_vals = [r['Ns'] for r in results]

    f, ax = plt.subplots(figsize=(9, 6))
    grid_r2 = [r['grid']['mean_r2'] for r in results]
    ax.plot(Ns_vals, grid_r2, '-o', color='#00e5ff', linewidth=1.8,
            markersize=6, label='grid fit')
    if not skip_final_fit:
        final_r2 = [r['final']['mean_r2'] for r in results]
        ax.plot(Ns_vals, final_r2, '-s', color='#ff4081', linewidth=1.8,
                markersize=6, label='final fit')
    ax.set_title('Mean fitted R² vs grid size')
    ax.set_xlabel('Grid size (Ns)')
    ax.set_ylabel('Mean R²')
    ax.grid(True, alpha=0.3)
    ax.legend(fontsize=10, framealpha=0.3)

    plt.tight_layout()
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close(f)
    print(f'R²-vs-Ns plot saved to {save_path}')


def plot_runtime_vs_ns(results, save_path, skip_final_fit):
    """Grid-fit (and final-fit) wall-clock time vs Ns, plus grid-point count."""
    Ns_vals = [r['Ns'] for r in results]

    f, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

    grid_t = [r['grid_fit_time'] for r in results]
    ax1.plot(Ns_vals, grid_t, '-o', color='#00e5ff', linewidth=1.8,
             markersize=6, label='grid fit')
    if not skip_final_fit:
        final_t = [r['final_fit_time'] for r in results]
        ax1.plot(Ns_vals, final_t, '-s', color='#ff4081', linewidth=1.8,
                 markersize=6, label='final fit')
    ax1.set_title('Fit runtime vs grid size')
    ax1.set_xlabel('Grid size (Ns)')
    ax1.set_ylabel('Wall-clock time (s)')
    ax1.grid(True, alpha=0.3)
    ax1.legend(fontsize=10, framealpha=0.3)

    n_points = [r['n_grid_points'] for r in results]
    ax2.plot(Ns_vals, n_points, '-o', color='#ffb300', linewidth=1.8, markersize=6)
    ax2.set_title('Constrained grid-point count vs grid size')
    ax2.set_xlabel('Grid size (Ns)')
    ax2.set_ylabel('# grid points')
    ax2.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close(f)
    print(f'Runtime-vs-Ns plot saved to {save_path}')


def save_metrics(results, save_path, skip_final_fit):
    """Persist the sweep metrics as a .npz for downstream inspection."""
    Ns_vals = np.array([r['Ns'] for r in results])
    payload = {
        'Ns': Ns_vals,
        'n_grid_points': np.array([r['n_grid_points'] for r in results]),
        'grid_fit_time': np.array([r['grid_fit_time'] for r in results]),
        'final_fit_time': np.array([r['final_fit_time'] for r in results]),
        'grid_mean_r2': np.array([r['grid']['mean_r2'] for r in results]),
        'n_grid_values': np.array(N_GRID_VALUES),
    }
    for name, _ in CORR_PARAMS:
        payload[f'grid_corr_{name}'] = np.array([r['grid']['corr'][name] for r in results])
        if not skip_final_fit:
            payload[f'final_corr_{name}'] = np.array([r['final']['corr'][name] for r in results])
    if not skip_final_fit:
        payload['final_mean_r2'] = np.array([r['final']['mean_r2'] for r in results])

    np.savez(save_path, **payload)
    print(f'Sweep metrics saved to {save_path}')


# Ground truth is loaded once and shared across all Ns (module-level so the
# per-Ns fit helper can reference it without re-threading it through every call).
trueFit_data_global = None


def main():
    args = parse_args()
    codeStartTime = time.perf_counter()

    params = dict(DEFAULT_PARAMS)
    params['subjID'] = 'JC'
    p, _ = set_paths(params['subjID'], data_format='volumetric')

    # ── Logging setup ──────────────────────────────────────────────────────────
    log_dir = os.path.join(p['pRF_data'], 'Simulation', 'logs')
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    log_path = os.path.join(log_dir, f'S03_{timestamp}.log')
    logger = TeeLogger(log_path)
    sys.stdout = logger
    sys.stderr = logger
    # ───────────────────────────────────────────────────────────────────────────

    try:
        _run(args, codeStartTime, p, params)
    except Exception:
        traceback.print_exc()
        raise
    finally:
        print(f'\nLog saved to: {log_path}')
        logger.close()


def _run(args, codeStartTime, p, params):
    global trueFit_data_global
    set_dark_theme()

    # Load simulation data (shared across the whole sweep).
    print('Loading simulated data...')
    scan_data, trueFit_data = load_simulation_data(p, args.n_voxels)
    trueFit_data_global = trueFit_data
    nvoxs = scan_data.shape[0]

    print('=== Grid-size Sweep (S03) ===')
    print(f'Run started: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}')
    print(f'N voxels:    {nvoxs}')
    print(f'Grid sizes:  {args.grid_sizes}')
    print(f'n-grid:      {N_GRID_VALUES} ({len(N_GRID_VALUES)} values)')
    print(f'GPU:         {"enabled" if args.use_gpu else "disabled"}')
    print(f'Final fit:   {"skipped" if args.skip_final_fit else "enabled"}')
    if not args.skip_final_fit:
        print(f'  n_iter:    {args.n_iter}')
        print(f'  lr:        {args.lr}')
        print(f'  sub_batch: {args.sub_batch if args.sub_batch is not None else "auto"}')
    print()

    # Detrend once.
    timeseries_data = remove_trend(scan_data, method='all')
    indices = [(0, 0, i) for i in range(nvoxs)]

    # Load stimulus once (identical across Ns).
    bar, _ = load_stimuli(p)
    bar = bar[:, :, 0:201]
    bar = np.flip(bar, axis=0)
    func_img = nib.load(p['pRF_ss5'])
    stimulus = VisualStimulus(
        bar.astype('int16'),
        params['viewingDistance'],
        params['screenWidth'],
        params['scaleFactor'],
        float(func_img.header['pixdim'][4]),
        params['dtype'],
    )

    # Sweep.
    results = []
    for Ns in args.grid_sizes:
        results.append(
            fit_one_gridsize(Ns, stimulus, timeseries_data, indices, nvoxs, p,
                             args.use_gpu, args.skip_final_fit,
                             n_iter=args.n_iter, lr=args.lr, sub_batch=args.sub_batch)
        )

    # Outputs.
    fig_dir = os.path.join(p['pRF_data'], 'Simulation', 'figures', 'gridsize_sweep')
    os.makedirs(fig_dir, exist_ok=True)

    plot_accuracy_vs_ns(results, os.path.join(fig_dir, 'accuracy_vs_Ns.png'),
                        args.skip_final_fit)
    plot_r2_vs_ns(results, os.path.join(fig_dir, 'r2_vs_Ns.png'),
                  args.skip_final_fit)
    plot_runtime_vs_ns(results, os.path.join(fig_dir, 'runtime_vs_Ns.png'),
                       args.skip_final_fit)
    save_metrics(results, os.path.join(fig_dir, 'sweep_metrics.npz'),
                 args.skip_final_fit)

    codeEndTime = time.perf_counter()
    print_time(codeStartTime, codeEndTime, 'Total grid-size sweep')


if __name__ == '__main__':
    main()
