"""
S03_gridsize_sweep.py — Sweep grid density (Ns) on simulated data to find the optimal grid size.

Loads the synthetic data generated by S01_simulate_prf.py and, for each Ns in a
sweep, runs the full grid fit + final fit and records how well each parameter is
recovered relative to ground truth. Produces "accuracy vs Ns" and "runtime vs Ns"
summary figures — the two sides of the grid-density cost/benefit tradeoff.

Differences from S02_run_simulation_fit.py:
  * Loops over many Ns values (default: 10, 20, ..., 100) in one process.
  * Uses a finer CSS exponent (n) grid — 10 values instead of the default 4 —
    since the exponent is the parameter most sensitive to grid resolution.
  * GPU is the default (pass --no-gpu to disable).
  * Grid predictions are cached under an S03-specific name that also encodes the
    n-grid resolution, so they never collide with S02's `gridfit_{Ns}.npy` caches
    (the grid spaces differ).

Usage:
    python S03_gridsize_sweep.py
    python S03_gridsize_sweep.py --grid-sizes 10 20 30 40 50 60 70 80 90 100
    python S03_gridsize_sweep.py --n-voxels 5000 --no-gpu
"""

import argparse
import time
import os
import sys
import traceback
from datetime import datetime

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.colors import Normalize
import nibabel as nib

from itertools import product
from concurrent.futures import ThreadPoolExecutor

from popeye.visual_stimulus import VisualStimulus

from H01_config import DEFAULT_PARAMS, GRID_DEFAULTS, set_paths, get_gridfit_path
from H02_dataloader import load_stimuli
from H03_fit_utils import print_time, remove_trend, constraint_grids, set_dark_theme
from H04_grid_predict import getGridPreds
from H05_grid_fit import get_grid_estims
from H06_final_fit import get_final_estims
from D01_analyze_snr import compute_tfsp

# Reuse S02's simulation loader and tee logger to avoid duplication.
from S02_run_simulation_fit import TeeLogger, load_simulation_data


# Finer CSS exponent grid for the sweep (10 values vs the coarse 4). Shared with
# S02 via H01_config so both build the same grid and reuse the same cache file.
N_GRID_VALUES = GRID_DEFAULTS['n_grid_values_fine']

# TFSP task-band period (seconds); matches S02. TFSP (SNR) is used only to color
# the recovery-scatter points.
TFSP_SWEEP_PERIOD_S = 25.0

# Column layout of the 9-element CSS estimate (ground truth uses the same layout):
#   0 theta (polar angle, rad)  1 R² (model fit)  2 rho (ecc, deg)  3 sigma (deg)
#   4 n (CSS exponent)          5 x (deg)         6 y (deg)         7 beta  8 baseline
#
# Parameters scored by *recovery error* (fitted vs ground truth), not correlation.
# Pearson r is scale/offset-invariant (hides bias) and invalid for the circular
# theta; position is scored as a 2D Euclidean distance and theta circularly.
ERROR_PARAMS = ['position', 'theta', 'sigma', 'n']
ERROR_UNITS = {'position': 'deg', 'theta': 'deg', 'sigma': 'deg', 'n': ''}

# Parameters shown as fitted-vs-true identity scatters: (name, column, unit).
SCATTER_PARAMS = [('rho', 2, 'deg'), ('theta', 0, 'deg'),
                  ('sigma', 3, 'deg'), ('n', 4, '')]


def parse_args():
    parser = argparse.ArgumentParser(
        description='Sweep grid density (Ns) on simulated data and evaluate accuracy vs runtime'
    )
    parser.add_argument('--grid-sizes', type=int, nargs='+',
                        default=[10, 20, 30, 40, 50, 60, 70],
                        help='Grid densities Ns to sweep (default: 10..70 by 10)')
    parser.add_argument('--n-voxels', type=int, default=None,
                        help='Number of voxels to test (default: all simulated voxels)')
    parser.add_argument('--no-gpu', dest='use_gpu', action='store_false',
                        help='Disable GPU acceleration (GPU is used by default)')
    parser.add_argument('--skip-final-fit', action='store_true',
                        help='Run coarse grid fit only; skip the final fit step')
    parser.add_argument('--n-iter', type=int, default=300,
                        help='Adam iterations per sub-batch in the GPU final fit (default: 300)')
    parser.add_argument('--lr', type=float, default=0.005,
                        help='Adam learning rate for the GPU final fit (default: 0.005)')
    parser.add_argument('--sub-batch', type=int, default=None,
                        help='Voxels per GPU sub-batch (default: auto-size from free VRAM)')
    parser.add_argument('--no-prefetch', action='store_true',
                        help='Disable overlapping next-Ns grid prediction with the current '
                             'GPU fit (run fully sequentially)')
    parser.add_argument('--plot-only', action='store_true',
                        help='Skip fitting; rebuild figures/metrics from grid/final fit '
                             '.npy files already saved under Simulation/popeyeFit/S03/')
    parser.set_defaults(use_gpu=True)
    return parser.parse_args()


def build_grid_space(stimulus, Ns):
    """Build the (x, y, sigma, n) grid space for a given Ns, using the fine n grid.

    Mirrors the grid construction in S02 but substitutes the 10-point n grid.
    Returns (grid_space, param_width).
    """
    x_grid = np.concatenate((
        np.linspace(-stimulus.deg_x0.max(), stimulus.deg_x0.max(), Ns // 2),
        np.geomspace(-stimulus.deg_x0.max(), -2 * stimulus.deg_x0.max(), Ns // 4),
        np.geomspace(stimulus.deg_x0.max(), 2 * stimulus.deg_x0.max(), Ns // 4),
    ))
    y_grid = np.concatenate((
        np.linspace(-stimulus.deg_y0.max(), stimulus.deg_y0.max(), Ns // 2),
        np.geomspace(-stimulus.deg_y0.max(), -2 * stimulus.deg_y0.max(), Ns // 4),
        np.geomspace(stimulus.deg_y0.max(), 2 * stimulus.deg_y0.max(), Ns // 4),
    ))
    s_grid = np.concatenate((
        np.linspace(0.1, 5, 3 * Ns // 4),
        np.geomspace(5, stimulus.deg_x0.max(), Ns // 4),
    ))
    n_grid = np.asarray(N_GRID_VALUES)

    grid_space_orig = list(product(x_grid, y_grid, s_grid, n_grid))
    grid_space = constraint_grids(grid_space_orig, stimulus)

    param_width = [np.mean(np.diff(x_grid)), np.mean(np.diff(y_grid)),
                   np.mean(np.diff(s_grid)), np.mean(np.diff(n_grid))]
    return grid_space, param_width


def circular_error_deg(theta_true, theta_fit):
    """Signed angular error (fit − true) wrapped to [−180°, 180°].

    Linear differences on polar angle are wrong across the 0↔2π boundary; the
    arctan2(sin, cos) trick maps the difference back onto the shortest arc.
    """
    d = np.asarray(theta_fit, dtype=float) - np.asarray(theta_true, dtype=float)
    return np.degrees(np.arctan2(np.sin(d), np.cos(d)))


def per_voxel_errors(trueFit_data, fitted_data):
    """Per-voxel error array for each ERROR_PARAMS entry.

    position → Euclidean RF-center distance (deg, ≥0)
    theta    → circular angular error (deg, signed, in [−180, 180])
    sigma, n → signed error (fit − true), so median bias is meaningful
    """
    t = np.asarray(trueFit_data, dtype=float)
    fdat = np.asarray(fitted_data, dtype=float)
    return {
        'position': np.hypot(fdat[:, 5] - t[:, 5], fdat[:, 6] - t[:, 6]),
        'theta': circular_error_deg(t[:, 0], fdat[:, 0]),
        'sigma': fdat[:, 3] - t[:, 3],
        'n': fdat[:, 4] - t[:, 4],
    }


def compute_metrics(trueFit_data, fitted_data):
    """Return (per-voxel error dict, mean model-fit R²).

    The error dict feeds every accuracy summary (MAE/RMSE/bias/IQR are derived
    at plot time so voxel-level spread is preserved). ``mean_r2`` is the model's
    own goodness-of-fit (col 1) — model quality, NOT parameter recovery.
    """
    errs = per_voxel_errors(trueFit_data, fitted_data)
    mean_r2 = float(np.nanmean(fitted_data[:, 1]))
    return errs, mean_r2


def _err_summary(err):
    """(MAE, RMSE, median-bias, |err| q25, |err| q75) over finite entries."""
    e = np.asarray(err, dtype=float)
    e = e[np.isfinite(e)]
    if e.size == 0:
        return (np.nan, np.nan, np.nan, np.nan, np.nan)
    ae = np.abs(e)
    return (float(np.mean(ae)), float(np.sqrt(np.mean(e ** 2))),
            float(np.median(e)), float(np.percentile(ae, 25)),
            float(np.percentile(ae, 75)))


def prepare_gridpreds(Ns, stimulus, p, nTRs):
    """CPU stage: build the grid space and load-or-generate its grid predictions.

    This is the only compute-heavy CPU step (`getGridPreds` uses a process Pool)
    and is independent of the GPU fit, so it can run for Ns=(k+1) while the GPU
    fits Ns=k. Returns (grid_space, param_width, grid_preds, prep_time).
    """
    t0 = time.perf_counter()
    grid_space, param_width = build_grid_space(stimulus, Ns)
    print(f'[Ns={Ns}] Grid space: {len(grid_space)} points '
          f'(n-grid resolution = {len(N_GRID_VALUES)})')

    gridfit_path = get_gridfit_path(p, Ns, n_res=len(N_GRID_VALUES))
    if os.path.exists(gridfit_path):
        print(f'[Ns={Ns}] Loading grid predictions from disk ({gridfit_path})')
        grid_preds = np.load(gridfit_path)
    else:
        print(f'[Ns={Ns}] Generating grid predictions ({gridfit_path})...')
        grid_preds = getGridPreds(grid_space, stimulus, gridfit_path, nTRs)
    prep_time = time.perf_counter() - t0
    print_time(t0, time.perf_counter(), f'[Ns={Ns}] Grid predictions')
    return grid_space, param_width, grid_preds, prep_time


def fit_from_preds(Ns, grid_space, param_width, grid_preds, prep_time,
                   stimulus, timeseries_data, indices, nvoxs, use_gpu,
                   skip_final_fit, fit_dir,
                   n_iter=300, lr=0.005, sub_batch=None):
    """GPU stage: grid fit (+ optional final fit) from precomputed predictions.

    Runs on the main thread so all CuPy work stays on a single device context.
    Grid- and final-fit estimates are saved to ``fit_dir`` (the S03 subfolder).
    """
    print(f'\n{"="*70}\n=== Ns = {Ns} ===\n{"="*70}')

    # Grid fit.
    print('Starting grid fit...')
    t_pred = time.perf_counter()
    RF_gFit = np.empty((1, 1, nvoxs, 9))
    RF_gFit = get_grid_estims(grid_preds, grid_space, timeseries_data,
                              RF_gFit, indices, use_gpu=use_gpu)
    t_grid = time.perf_counter()
    grid_time = t_grid - t_pred
    print_time(t_pred, t_grid, f'[Ns={Ns}] Grid fit')

    result = {
        'Ns': Ns,
        'n_grid_points': len(grid_space),
        'grid_prep_time': prep_time,
        'grid_fit_time': grid_time,
        'grid': None,
        'final': None,
    }
    gfit_save_path = os.path.join(fit_dir, f'RF_ss5_gFit_popeye_Ns{Ns}.npy')
    np.save(gfit_save_path, RF_gFit[0, 0, :, :])
    print(f'[Ns={Ns}] Grid-fit estimates saved to {gfit_save_path}')

    grid_errs, grid_r2 = compute_metrics(trueFit_data_global, RF_gFit[0, 0, :, :])
    result['grid'] = {'errs': grid_errs, 'mean_r2': grid_r2}

    # Final fit (optional).
    if not skip_final_fit:
        print('Starting final fit...')
        RF_fFit = np.empty((1, 1, nvoxs, 9))
        RF_fFit = get_final_estims(RF_gFit, param_width, timeseries_data,
                                   stimulus, RF_fFit, indices, use_gpu=use_gpu,
                                   n_iter=n_iter, lr=lr, sub_batch=sub_batch)
        RF_fFit = RF_fFit.reshape(1, 1, nvoxs, 9)
        t_final = time.perf_counter()
        result['final_fit_time'] = t_final - t_grid
        print_time(t_grid, t_final, f'[Ns={Ns}] Final fit')

        ffit_save_path = os.path.join(fit_dir, f'RF_ss5_fFit_popeye_Ns{Ns}.npy')
        np.save(ffit_save_path, RF_fFit[0, 0, :, :])
        print(f'[Ns={Ns}] Final-fit estimates saved to {ffit_save_path}')

        final_errs, final_r2 = compute_metrics(trueFit_data_global, RF_fFit[0, 0, :, :])
        result['final'] = {'errs': final_errs, 'mean_r2': final_r2}
    else:
        result['final_fit_time'] = np.nan

    return result


def build_results_from_saved(grid_sizes, fit_dir, stimulus, trueFit_data,
                             skip_final_fit):
    """Reconstruct sweep results from previously saved grid/final fit .npy files.

    Used by --plot-only when a run was interrupted before the in-memory plotting
    step. Recomputes accuracy/R² metrics against ground truth for each Ns whose
    fits are present; timing is unavailable (not persisted) and set to NaN.

    Returns (results, effective_skip) where effective_skip is True if no final
    fits were found (so downstream plots show grid only).
    """
    def gpath(Ns):
        return os.path.join(fit_dir, f'RF_ss5_gFit_popeye_Ns{Ns}.npy')

    def fpath(Ns):
        return os.path.join(fit_dir, f'RF_ss5_fFit_popeye_Ns{Ns}.npy')

    any_final = any(os.path.exists(fpath(Ns)) for Ns in grid_sizes)
    use_final = (not skip_final_fit) and any_final
    if (not skip_final_fit) and not any_final:
        print('[plot-only] No final-fit files found — plotting grid fit only.')

    results = []
    for Ns in grid_sizes:
        if not os.path.exists(gpath(Ns)):
            print(f'[plot-only] Ns={Ns}: no grid fit at {gpath(Ns)} — skipping')
            continue
        if use_final and not os.path.exists(fpath(Ns)):
            print(f'[plot-only] Ns={Ns}: final fit missing — skipping for consistency')
            continue

        gfit = np.load(gpath(Ns))
        n = min(len(trueFit_data), len(gfit))
        grid_space, _ = build_grid_space(stimulus, Ns)
        gerrs, gr2 = compute_metrics(trueFit_data[:n], gfit[:n])
        res = {
            'Ns': Ns,
            'n_grid_points': len(grid_space),
            'grid_prep_time': np.nan,
            'grid_fit_time': np.nan,
            'final_fit_time': np.nan,
            'grid': {'errs': gerrs, 'mean_r2': gr2},
            'final': None,
        }
        if use_final:
            ffit = np.load(fpath(Ns))
            m = min(len(trueFit_data), len(ffit))
            ferrs, fr2 = compute_metrics(trueFit_data[:m], ffit[:m])
            res['final'] = {'errs': ferrs, 'mean_r2': fr2}
        results.append(res)
        print(f'[plot-only] Ns={Ns}: loaded ({"grid+final" if use_final else "grid"})')

    return results, (not use_final)


def plot_accuracy_vs_ns(results, save_path, skip_final_fit):
    """One panel per parameter: recovery error vs Ns (lower = better).

    Solid line = MAE (mean |error|) with an IQR band for voxel-level spread;
    grid (cyan) vs final (pink). For sigma/n the median *signed* bias is overlaid
    (dashed) — this is what Pearson r structurally hid (a scaled/offset fit can
    score r≈1 yet carry a large systematic bias).
    """
    Ns_vals = [r['Ns'] for r in results]

    stages = [('grid', 'grid fit', '#00e5ff', 'o')]
    if not skip_final_fit:
        stages.append(('final', 'final fit', '#ff4081', 's'))

    # Panels: the four recovery-error parameters + a model-fit-R² panel (the old
    # r2_vs_Ns figure, folded in here). 5 panels in a 2×3 grid; last is hidden.
    panels = ERROR_PARAMS + ['r2']
    f, axs = plt.subplots(2, 3, figsize=(18, 10))
    axs = axs.flatten()
    for ax, name in zip(axs, panels):
        if name == 'r2':
            # Model goodness-of-fit (higher = better) — NOT recovery accuracy.
            for key, label, color, marker in stages:
                r2 = [r[key]['mean_r2'] for r in results]
                ax.plot(Ns_vals, r2, '-', marker=marker, color=color,
                        linewidth=1.8, markersize=5, label=label)
            ax.set_title('model fit R² vs Ns (goodness-of-fit, higher = better)')
            ax.set_xlabel('Grid size (Ns)')
            ax.set_ylabel('Mean model-fit R²')
            ax.grid(True, alpha=0.3)
            ax.legend(fontsize=8, framealpha=0.3)
            continue
        unit = ERROR_UNITS[name]
        usuffix = f' ({unit})' if unit else ''
        for key, label, color, marker in stages:
            summ = [_err_summary(r[key]['errs'][name]) for r in results]
            mae = [s[0] for s in summ]
            q25 = [s[3] for s in summ]
            q75 = [s[4] for s in summ]
            ax.plot(Ns_vals, mae, '-', marker=marker, color=color, linewidth=1.8,
                    markersize=5, label=f'{label} MAE')
            ax.fill_between(Ns_vals, q25, q75, color=color, alpha=0.15)
            if name in ('sigma', 'n'):
                bias = [s[2] for s in summ]
                ax.plot(Ns_vals, bias, '--', color=color, linewidth=1.2,
                        alpha=0.85, label=f'{label} bias')
        ax.axhline(0, color='#888888', linewidth=0.8, alpha=0.5)
        ax.set_title(f'{name}: recovery error vs Ns{usuffix} (lower = better)')
        ax.set_xlabel('Grid size (Ns)')
        ax.set_ylabel(f'Error{usuffix}  (MAE; band = IQR)')
        ax.grid(True, alpha=0.3)
        ax.legend(fontsize=8, framealpha=0.3)

    # Hide unused panels (5 used of 6).
    for ax in axs[len(panels):]:
        ax.set_visible(False)

    f.suptitle('Parameter recovery & fit quality vs grid size', fontsize=15)
    plt.tight_layout()
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close(f)
    print(f'Accuracy-vs-Ns plot saved to {save_path}')


def plot_recovery_scatter(results, save_path, fit_dir, trueFit_data, tfsp,
                          skip_final_fit):
    """Fitted-vs-true identity scatters, one column per swept Ns.

    Rows = SCATTER_PARAMS (rho, theta, sigma, n), columns = every grid size in the
    sweep. Points are colored by TFSP (SNR); the pink dashed line is y=x, and each
    panel is annotated with MAE and median bias. Fits are reloaded from the saved
    .npy estimates, so this works identically in the live sweep and in
    --plot-only. Uses the final fit when available, otherwise the grid fit.
    """
    reps = sorted({r['Ns'] for r in results})
    if not reps:
        return

    use_final = not skip_final_fit
    stage = 'fFit' if use_final else 'gFit'
    stage_label = 'final fit' if use_final else 'grid fit'

    t = np.asarray(trueFit_data, dtype=float)
    tfsp = np.asarray(tfsp, dtype=float).flatten()
    finite_tfsp = tfsp[np.isfinite(tfsp)]
    if finite_tfsp.size:
        cnorm = Normalize(vmin=float(np.percentile(finite_tfsp, 1)),
                          vmax=float(np.percentile(finite_tfsp, 99)))
    else:
        cnorm = Normalize(vmin=0.0, vmax=1.0)

    nrows, ncols = len(SCATTER_PARAMS), len(reps)
    f, axs = plt.subplots(nrows, ncols, figsize=(5 * ncols, 4.2 * nrows),
                          squeeze=False, layout='constrained')
    last_sc = None
    for j, Ns in enumerate(reps):
        path = os.path.join(fit_dir, f'RF_ss5_{stage}_popeye_Ns{Ns}.npy')
        if not os.path.exists(path):
            path = os.path.join(fit_dir, f'RF_ss5_gFit_popeye_Ns{Ns}.npy')
        if not os.path.exists(path):
            continue
        fit = np.load(path)
        n = min(len(t), len(fit), len(tfsp))
        tf, ff, c = t[:n], fit[:n], tfsp[:n]
        for i, (name, col, unit) in enumerate(SCATTER_PARAMS):
            ax = axs[i][j]
            xt, yf = tf[:, col], ff[:, col]
            if name == 'theta':
                xt, yf = np.degrees(xt), np.degrees(yf)
                err = circular_error_deg(tf[:, col], ff[:, col])
            else:
                err = yf - xt
            m = np.isfinite(xt) & np.isfinite(yf)
            last_sc = ax.scatter(xt[m], yf[m], c=c[m], s=6, cmap='viridis',
                                 norm=cnorm, alpha=0.6, linewidths=0)
            if m.any():
                lo = float(min(xt[m].min(), yf[m].min()))
                hi = float(max(xt[m].max(), yf[m].max()))
                ax.plot([lo, hi], [lo, hi], color='#ff4081', linewidth=1.0,
                        linestyle='--')
            usuffix = f' ({unit})' if unit else ''
            mae = float(np.nanmean(np.abs(err)))
            bias = float(np.nanmedian(err))
            ax.set_title(f'Ns={Ns}  {name}', fontsize=10)
            ax.set_xlabel(f'true {name}{usuffix}')
            ax.set_ylabel(f'fit {name}{usuffix}')
            ax.text(0.05, 0.95, f'MAE={mae:.3g}\nbias={bias:.3g}',
                    transform=ax.transAxes, va='top', ha='left', fontsize=8,
                    color='#e0e0e0',
                    bbox=dict(boxstyle='round', fc='#222222', ec='none', alpha=0.6))
            ax.grid(True, alpha=0.2)

    if last_sc is not None:
        cb = f.colorbar(last_sc, ax=axs.ravel().tolist(), fraction=0.025, pad=0.02)
        cb.set_label('TFSP (SNR)')
    f.suptitle(f'Fitted vs true ({stage_label}); dashed = identity, color = TFSP',
               fontsize=15)
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close(f)
    print(f'Recovery-scatter plot saved to {save_path}')


def plot_runtime_vs_ns(results, save_path, skip_final_fit):
    """Grid-fit (and final-fit) wall-clock time vs Ns, plus grid-point count."""
    Ns_vals = [r['Ns'] for r in results]

    f, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

    grid_t = [r['grid_fit_time'] for r in results]
    ax1.plot(Ns_vals, grid_t, '-o', color='#00e5ff', linewidth=1.8,
             markersize=6, label='grid fit')
    if not skip_final_fit:
        final_t = [r['final_fit_time'] for r in results]
        ax1.plot(Ns_vals, final_t, '-s', color='#ff4081', linewidth=1.8,
                 markersize=6, label='final fit')
    ax1.set_title('Fit runtime vs grid size')
    ax1.set_xlabel('Grid size (Ns)')
    ax1.set_ylabel('Wall-clock time (s)')
    ax1.grid(True, alpha=0.3)
    ax1.legend(fontsize=10, framealpha=0.3)

    n_points = [r['n_grid_points'] for r in results]
    ax2.plot(Ns_vals, n_points, '-o', color='#ffb300', linewidth=1.8, markersize=6)
    ax2.set_title('Constrained grid-point count vs grid size')
    ax2.set_xlabel('Grid size (Ns)')
    ax2.set_ylabel('# grid points')
    ax2.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close(f)
    print(f'Runtime-vs-Ns plot saved to {save_path}')


def save_metrics(results, save_path, skip_final_fit):
    """Persist the sweep metrics as a .npz for downstream inspection.

    Per-parameter recovery error is stored as MAE / RMSE / median-bias vectors
    (indexed by Ns) for each ERROR_PARAMS entry, plus the mean model-fit R².
    """
    def err_vecs(key, name):
        summ = [_err_summary(r[key]['errs'][name]) for r in results]
        return (np.array([s[0] for s in summ]),   # MAE
                np.array([s[1] for s in summ]),   # RMSE
                np.array([s[2] for s in summ]))   # median bias

    payload = {
        'Ns': np.array([r['Ns'] for r in results]),
        'n_grid_points': np.array([r['n_grid_points'] for r in results]),
        'grid_prep_time': np.array([r['grid_prep_time'] for r in results]),
        'grid_fit_time': np.array([r['grid_fit_time'] for r in results]),
        'final_fit_time': np.array([r['final_fit_time'] for r in results]),
        'grid_mean_r2': np.array([r['grid']['mean_r2'] for r in results]),
        'n_grid_values': np.array(N_GRID_VALUES),
    }
    for name in ERROR_PARAMS:
        mae, rmse, bias = err_vecs('grid', name)
        payload[f'grid_mae_{name}'] = mae
        payload[f'grid_rmse_{name}'] = rmse
        payload[f'grid_bias_{name}'] = bias
        if not skip_final_fit:
            fmae, frmse, fbias = err_vecs('final', name)
            payload[f'final_mae_{name}'] = fmae
            payload[f'final_rmse_{name}'] = frmse
            payload[f'final_bias_{name}'] = fbias
    if not skip_final_fit:
        payload['final_mean_r2'] = np.array([r['final']['mean_r2'] for r in results])

    np.savez(save_path, **payload)
    print(f'Sweep metrics saved to {save_path}')


# Ground truth is loaded once and shared across all Ns (module-level so the
# per-Ns fit helper can reference it without re-threading it through every call).
trueFit_data_global = None


def main():
    args = parse_args()
    codeStartTime = time.perf_counter()

    params = dict(DEFAULT_PARAMS)
    params['subjID'] = 'JC'
    p, _ = set_paths(params['subjID'], data_format='volumetric')

    # ── Logging setup ──────────────────────────────────────────────────────────
    log_dir = os.path.join(p['pRF_data'], 'Simulation', 'logs')
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    log_path = os.path.join(log_dir, f'S03_{timestamp}.log')
    logger = TeeLogger(log_path)
    sys.stdout = logger
    sys.stderr = logger
    # ───────────────────────────────────────────────────────────────────────────

    try:
        _run(args, codeStartTime, p, params)
    except Exception:
        traceback.print_exc()
        raise
    finally:
        print(f'\nLog saved to: {log_path}')
        logger.close()


def _run(args, codeStartTime, p, params):
    global trueFit_data_global
    set_dark_theme()

    # Load simulation data (shared across the whole sweep).
    print('Loading simulated data...')
    scan_data, trueFit_data = load_simulation_data(p, args.n_voxels)
    trueFit_data_global = trueFit_data
    nvoxs = scan_data.shape[0]

    print('=== Grid-size Sweep (S03) ===')
    print(f'Run started: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}')
    print(f'Mode:        {"plot-only (rebuild figures from saved fits)" if args.plot_only else "fit + plot"}')
    print(f'N voxels:    {nvoxs}')
    print(f'Grid sizes:  {args.grid_sizes}')
    print(f'n-grid:      {N_GRID_VALUES} ({len(N_GRID_VALUES)} values)')
    if not args.plot_only:
        print(f'GPU:         {"enabled" if args.use_gpu else "disabled"}')
        print(f'Prefetch:    {"disabled" if args.no_prefetch else "enabled (depth 1)"}')
        print(f'Final fit:   {"skipped" if args.skip_final_fit else "enabled"}')
        if not args.skip_final_fit:
            print(f'  n_iter:    {args.n_iter}')
            print(f'  lr:        {args.lr}')
            print(f'  sub_batch: {args.sub_batch if args.sub_batch is not None else "auto"}')
    print()

    # Detrend once.
    timeseries_data = remove_trend(scan_data, method='all')
    indices = [(0, 0, i) for i in range(nvoxs)]

    # Load stimulus once (identical across Ns).
    bar, _ = load_stimuli(p)
    bar = bar[:, :, 0:201]
    bar = np.flip(bar, axis=0)
    func_img = nib.load(p['pRF_ss5'])
    stimulus = VisualStimulus(
        bar.astype('int16'),
        params['viewingDistance'],
        params['screenWidth'],
        params['scaleFactor'],
        float(func_img.header['pixdim'][4]),
        params['dtype'],
    )

    # TFSP (SNR) per voxel, computed once from the detrended data (independent of
    # Ns). Used to color the recovery-scatter points by SNR.
    print('Computing TFSP (SNR) per voxel...')
    tfsp, _, _, _ = compute_tfsp(timeseries_data, tr=params['tr_length'],
                                 sweep_period_s=TFSP_SWEEP_PERIOD_S)

    # All S03 outputs live under dedicated S03 subfolders of the usual dirs.
    fit_dir = os.path.join(p['pRF_data'], 'Simulation', 'popeyeFit', 'S03')
    os.makedirs(fit_dir, exist_ok=True)
    fig_dir = os.path.join(p['pRF_data'], 'Simulation', 'figures', 'S03')
    os.makedirs(fig_dir, exist_ok=True)

    grid_sizes = list(args.grid_sizes)
    effective_skip = args.skip_final_fit

    if args.plot_only:
        # Rebuild results from previously saved fits — no fitting.
        results, effective_skip = build_results_from_saved(
            grid_sizes, fit_dir, stimulus, trueFit_data, args.skip_final_fit)
        if not results:
            print('[plot-only] No saved fits found for the requested Ns — nothing to plot.')
            return
    else:
        # Sweep. The CPU grid-prediction of the next Ns is overlapped with the GPU
        # fit of the current Ns (prefetch depth 1), since they use disjoint resources
        # (process Pool vs GPU) and grid predictions are independent of the fit.
        nTRs = timeseries_data.shape[1]
        results = []

        def _prep(Ns):
            return prepare_gridpreds(Ns, stimulus, p, nTRs)

        if args.no_prefetch or len(grid_sizes) <= 1:
            for Ns in grid_sizes:
                grid_space, param_width, grid_preds, prep_time = _prep(Ns)
                results.append(
                    fit_from_preds(Ns, grid_space, param_width, grid_preds, prep_time,
                                   stimulus, timeseries_data, indices, nvoxs,
                                   args.use_gpu, args.skip_final_fit, fit_dir,
                                   n_iter=args.n_iter, lr=args.lr, sub_batch=args.sub_batch)
                )
        else:
            print(f'\nPrefetch enabled: overlapping next-Ns grid prediction with '
                  f'current-Ns GPU fit (depth 1).')
            with ThreadPoolExecutor(max_workers=1) as ex:
                fut = ex.submit(_prep, grid_sizes[0])
                for i, Ns in enumerate(grid_sizes):
                    grid_space, param_width, grid_preds, prep_time = fut.result()
                    # Kick off the next Ns's CPU prediction before we occupy the GPU.
                    if i + 1 < len(grid_sizes):
                        fut = ex.submit(_prep, grid_sizes[i + 1])
                    results.append(
                        fit_from_preds(Ns, grid_space, param_width, grid_preds, prep_time,
                                       stimulus, timeseries_data, indices, nvoxs,
                                       args.use_gpu, args.skip_final_fit, fit_dir,
                                       n_iter=args.n_iter, lr=args.lr, sub_batch=args.sub_batch)
                    )

    plot_accuracy_vs_ns(results, os.path.join(fig_dir, 'accuracy_vs_Ns.png'),
                        effective_skip)
    plot_recovery_scatter(results, os.path.join(fig_dir, 'recovery_scatter.png'),
                          fit_dir, trueFit_data, tfsp, effective_skip)
    if args.plot_only:
        print('[plot-only] Runtime figure skipped — per-Ns timing is not persisted.')
    else:
        plot_runtime_vs_ns(results, os.path.join(fig_dir, 'runtime_vs_Ns.png'),
                           effective_skip)
    save_metrics(results, os.path.join(fig_dir, 'sweep_metrics.npz'),
                 effective_skip)

    codeEndTime = time.perf_counter()
    print_time(codeStartTime, codeEndTime,
               'Total plot-only rebuild' if args.plot_only else 'Total grid-size sweep')


if __name__ == '__main__':
    main()
