"""
S03_gridsize_sweep.py — Sweep grid density (Ns) on simulated data to find the optimal grid size.

Loads the synthetic data generated by S01_simulate_prf.py and, for each Ns in a
sweep, runs the full grid fit + final fit and records how well each parameter is
recovered relative to ground truth. Produces "accuracy vs Ns" and "runtime vs Ns"
summary figures — the two sides of the grid-density cost/benefit tradeoff.

Differences from S02_run_simulation_fit.py:
  * Loops over many Ns values (default: 10, 20, ..., 100) in one process.
  * Uses a finer CSS exponent (n) grid — 10 values instead of the default 4 —
    since the exponent is the parameter most sensitive to grid resolution.
  * GPU is the default (pass --no-gpu to disable).
  * Grid predictions are cached under an S03-specific name that also encodes the
    n-grid resolution, so they never collide with S02's `gridfit_{Ns}.npy` caches
    (the grid spaces differ).

Usage:
    python S03_gridsize_sweep.py
    python S03_gridsize_sweep.py --grid-sizes 10 20 30 40 50 60 70 80 90 100
    python S03_gridsize_sweep.py --n-voxels 5000 --no-gpu
"""

import argparse
import time
import os
import sys
import traceback
from datetime import datetime

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.cm import ScalarMappable
from matplotlib.colors import Normalize
import nibabel as nib

from itertools import product
from concurrent.futures import ThreadPoolExecutor
from scipy import stats

from popeye.visual_stimulus import VisualStimulus

from H01_config import DEFAULT_PARAMS, set_paths
from H02_dataloader import load_stimuli
from H03_fit_utils import print_time, remove_trend, constraint_grids, set_dark_theme
from H04_grid_predict import getGridPreds
from H05_grid_fit import get_grid_estims
from H06_final_fit import get_final_estims
from D01_analyze_snr import compute_tfsp

# Reuse S02's simulation loader and tee logger to avoid duplication.
from S02_run_simulation_fit import TeeLogger, load_simulation_data


# Finer CSS exponent grid for the sweep (10 values vs the default 4).
N_GRID_VALUES = np.round(np.linspace(0.25, 1.0, 10), 4).tolist()

# Number of TFSP (SNR) bins for the R²-vs-Ns-by-SNR figure.
N_TFSP_BINS = 10

# TFSP task-band period (seconds); matches S02.
TFSP_SWEEP_PERIOD_S = 25.0

# Parameters plotted as identity scatters in S02 (i.e. those with a meaningful
# ground truth to correlate against). Index into the 9-element CSS estimate.
CORR_PARAMS = [
    ('theta', 0),
    ('rho', 2),
    ('sigma', 3),
    ('n', 4),
    ('x', 5),
    ('y', 6),
]


def parse_args():
    parser = argparse.ArgumentParser(
        description='Sweep grid density (Ns) on simulated data and evaluate accuracy vs runtime'
    )
    parser.add_argument('--grid-sizes', type=int, nargs='+',
                        default=[10, 20, 30, 40, 50, 60, 70],
                        help='Grid densities Ns to sweep (default: 10..70 by 10)')
    parser.add_argument('--n-voxels', type=int, default=None,
                        help='Number of voxels to test (default: all simulated voxels)')
    parser.add_argument('--no-gpu', dest='use_gpu', action='store_false',
                        help='Disable GPU acceleration (GPU is used by default)')
    parser.add_argument('--skip-final-fit', action='store_true',
                        help='Run coarse grid fit only; skip the final fit step')
    parser.add_argument('--n-iter', type=int, default=300,
                        help='Adam iterations per sub-batch in the GPU final fit (default: 300)')
    parser.add_argument('--lr', type=float, default=0.005,
                        help='Adam learning rate for the GPU final fit (default: 0.005)')
    parser.add_argument('--sub-batch', type=int, default=None,
                        help='Voxels per GPU sub-batch (default: auto-size from free VRAM)')
    parser.add_argument('--no-prefetch', action='store_true',
                        help='Disable overlapping next-Ns grid prediction with the current '
                             'GPU fit (run fully sequentially)')
    parser.add_argument('--plot-only', action='store_true',
                        help='Skip fitting; rebuild figures/metrics from grid/final fit '
                             '.npy files already saved under Simulation/popeyeFit/S03/')
    parser.set_defaults(use_gpu=True)
    return parser.parse_args()


def get_s03_gridfit_path(p, Ns, n_res):
    """Grid-prediction cache path for the sweep (encodes Ns and n-grid resolution).

    Lives alongside the other caches in ``Stimuli/gridestims/``. The Ns + n-res
    encoding keeps it distinct from the default ``gridfit_{Ns}.npy`` caches.
    """
    gridestims_dir = os.path.join(p['stimuli_path'], 'gridestims')
    os.makedirs(gridestims_dir, exist_ok=True)
    return os.path.join(gridestims_dir, f'gridfit_Ns{Ns}_n{n_res}.npy')


def build_grid_space(stimulus, Ns):
    """Build the (x, y, sigma, n) grid space for a given Ns, using the fine n grid.

    Mirrors the grid construction in S02 but substitutes the 10-point n grid.
    Returns (grid_space, param_width).
    """
    x_grid = np.concatenate((
        np.linspace(-stimulus.deg_x0.max(), stimulus.deg_x0.max(), Ns // 2),
        np.geomspace(-stimulus.deg_x0.max(), -2 * stimulus.deg_x0.max(), Ns // 4),
        np.geomspace(stimulus.deg_x0.max(), 2 * stimulus.deg_x0.max(), Ns // 4),
    ))
    y_grid = np.concatenate((
        np.linspace(-stimulus.deg_y0.max(), stimulus.deg_y0.max(), Ns // 2),
        np.geomspace(-stimulus.deg_y0.max(), -2 * stimulus.deg_y0.max(), Ns // 4),
        np.geomspace(stimulus.deg_y0.max(), 2 * stimulus.deg_y0.max(), Ns // 4),
    ))
    s_grid = np.concatenate((
        np.linspace(0.1, 5, 3 * Ns // 4),
        np.geomspace(5, stimulus.deg_x0.max(), Ns // 4),
    ))
    n_grid = np.asarray(N_GRID_VALUES)

    grid_space_orig = list(product(x_grid, y_grid, s_grid, n_grid))
    grid_space = constraint_grids(grid_space_orig, stimulus)

    param_width = [np.mean(np.diff(x_grid)), np.mean(np.diff(y_grid)),
                   np.mean(np.diff(s_grid)), np.mean(np.diff(n_grid))]
    return grid_space, param_width


def safe_pearsonr(true_vals, fit_vals):
    """Pearson r over finite pairs; NaN if too few or degenerate."""
    true_vals = np.asarray(true_vals, dtype=float).flatten()
    fit_vals = np.asarray(fit_vals, dtype=float).flatten()
    mask = np.isfinite(true_vals) & np.isfinite(fit_vals)
    if mask.sum() < 3:
        return np.nan
    tv, fv = true_vals[mask], fit_vals[mask]
    if np.std(tv) == 0 or np.std(fv) == 0:
        return np.nan
    return stats.pearsonr(tv, fv)[0]


def compute_metrics(trueFit_data, fitted_data):
    """Return (dict of param->Pearson r vs ground truth, mean R²)."""
    corr = {name: safe_pearsonr(trueFit_data[:, idx], fitted_data[:, idx])
            for name, idx in CORR_PARAMS}
    mean_r2 = float(np.nanmean(fitted_data[:, 1]))
    return corr, mean_r2


def compute_tfsp_bins(tfsp, n_bins):
    """Assign voxels to quantile (decile) TFSP bins.

    Quantile bins give ~equal voxel counts per bin and are robust to the skewed
    TFSP distribution. Returns (bin_labels (N,) in [0, n_bins-1], bin_medians
    (n_bins,) median TFSP per bin; NaN for any empty bin).
    """
    tfsp = np.asarray(tfsp).flatten()
    edges = np.quantile(tfsp, np.linspace(0, 1, n_bins + 1))
    # Interior edges only → digitize yields labels 0..n_bins-1.
    bin_labels = np.clip(np.digitize(tfsp, edges[1:-1]), 0, n_bins - 1)
    bin_medians = np.array([
        np.median(tfsp[bin_labels == b]) if np.any(bin_labels == b) else np.nan
        for b in range(n_bins)
    ])
    return bin_labels, bin_medians


def compute_r2_by_bin(r2_vals, bin_labels, n_bins):
    """Mean R² within each TFSP bin: (n_bins,), NaN for empty bins."""
    r2_vals = np.asarray(r2_vals).flatten()
    out = np.full(n_bins, np.nan)
    for b in range(n_bins):
        mask = (bin_labels == b) & np.isfinite(r2_vals)
        if mask.any():
            out[b] = float(np.mean(r2_vals[mask]))
    return out


def prepare_gridpreds(Ns, stimulus, p, nTRs):
    """CPU stage: build the grid space and load-or-generate its grid predictions.

    This is the only compute-heavy CPU step (`getGridPreds` uses a process Pool)
    and is independent of the GPU fit, so it can run for Ns=(k+1) while the GPU
    fits Ns=k. Returns (grid_space, param_width, grid_preds, prep_time).
    """
    t0 = time.perf_counter()
    grid_space, param_width = build_grid_space(stimulus, Ns)
    print(f'[Ns={Ns}] Grid space: {len(grid_space)} points '
          f'(n-grid resolution = {len(N_GRID_VALUES)})')

    gridfit_path = get_s03_gridfit_path(p, Ns, len(N_GRID_VALUES))
    if os.path.exists(gridfit_path):
        print(f'[Ns={Ns}] Loading grid predictions from disk ({gridfit_path})')
        grid_preds = np.load(gridfit_path)
    else:
        print(f'[Ns={Ns}] Generating grid predictions ({gridfit_path})...')
        grid_preds = getGridPreds(grid_space, stimulus, gridfit_path, nTRs)
    prep_time = time.perf_counter() - t0
    print_time(t0, time.perf_counter(), f'[Ns={Ns}] Grid predictions')
    return grid_space, param_width, grid_preds, prep_time


def fit_from_preds(Ns, grid_space, param_width, grid_preds, prep_time,
                   stimulus, timeseries_data, indices, nvoxs, use_gpu,
                   skip_final_fit, fit_dir, bin_labels, n_bins,
                   n_iter=300, lr=0.005, sub_batch=None):
    """GPU stage: grid fit (+ optional final fit) from precomputed predictions.

    Runs on the main thread so all CuPy work stays on a single device context.
    Grid- and final-fit estimates are saved to ``fit_dir`` (the S03 subfolder).
    ``bin_labels`` assigns each voxel to a TFSP bin so per-bin mean R² is recorded.
    """
    print(f'\n{"="*70}\n=== Ns = {Ns} ===\n{"="*70}')

    # Grid fit.
    print('Starting grid fit...')
    t_pred = time.perf_counter()
    RF_gFit = np.empty((1, 1, nvoxs, 9))
    RF_gFit = get_grid_estims(grid_preds, grid_space, timeseries_data,
                              RF_gFit, indices, use_gpu=use_gpu)
    t_grid = time.perf_counter()
    grid_time = t_grid - t_pred
    print_time(t_pred, t_grid, f'[Ns={Ns}] Grid fit')

    result = {
        'Ns': Ns,
        'n_grid_points': len(grid_space),
        'grid_prep_time': prep_time,
        'grid_fit_time': grid_time,
        'grid': None,
        'final': None,
    }
    gfit_save_path = os.path.join(fit_dir, f'RF_ss5_gFit_popeye_Ns{Ns}.npy')
    np.save(gfit_save_path, RF_gFit[0, 0, :, :])
    print(f'[Ns={Ns}] Grid-fit estimates saved to {gfit_save_path}')

    grid_corr, grid_r2 = compute_metrics(trueFit_data_global, RF_gFit[0, 0, :, :])
    result['grid'] = {
        'corr': grid_corr, 'mean_r2': grid_r2,
        'r2_by_bin': compute_r2_by_bin(RF_gFit[0, 0, :, 1], bin_labels, n_bins),
    }

    # Final fit (optional).
    if not skip_final_fit:
        print('Starting final fit...')
        RF_fFit = np.empty((1, 1, nvoxs, 9))
        RF_fFit = get_final_estims(RF_gFit, param_width, timeseries_data,
                                   stimulus, RF_fFit, indices, use_gpu=use_gpu,
                                   n_iter=n_iter, lr=lr, sub_batch=sub_batch)
        RF_fFit = RF_fFit.reshape(1, 1, nvoxs, 9)
        t_final = time.perf_counter()
        result['final_fit_time'] = t_final - t_grid
        print_time(t_grid, t_final, f'[Ns={Ns}] Final fit')

        ffit_save_path = os.path.join(fit_dir, f'RF_ss5_fFit_popeye_Ns{Ns}.npy')
        np.save(ffit_save_path, RF_fFit[0, 0, :, :])
        print(f'[Ns={Ns}] Final-fit estimates saved to {ffit_save_path}')

        final_corr, final_r2 = compute_metrics(trueFit_data_global, RF_fFit[0, 0, :, :])
        result['final'] = {
            'corr': final_corr, 'mean_r2': final_r2,
            'r2_by_bin': compute_r2_by_bin(RF_fFit[0, 0, :, 1], bin_labels, n_bins),
        }
    else:
        result['final_fit_time'] = np.nan

    return result


def build_results_from_saved(grid_sizes, fit_dir, stimulus, trueFit_data,
                             skip_final_fit, bin_labels, n_bins):
    """Reconstruct sweep results from previously saved grid/final fit .npy files.

    Used by --plot-only when a run was interrupted before the in-memory plotting
    step. Recomputes accuracy/R² metrics against ground truth for each Ns whose
    fits are present; timing is unavailable (not persisted) and set to NaN.

    Returns (results, effective_skip) where effective_skip is True if no final
    fits were found (so downstream plots show grid only).
    """
    def gpath(Ns):
        return os.path.join(fit_dir, f'RF_ss5_gFit_popeye_Ns{Ns}.npy')

    def fpath(Ns):
        return os.path.join(fit_dir, f'RF_ss5_fFit_popeye_Ns{Ns}.npy')

    any_final = any(os.path.exists(fpath(Ns)) for Ns in grid_sizes)
    use_final = (not skip_final_fit) and any_final
    if (not skip_final_fit) and not any_final:
        print('[plot-only] No final-fit files found — plotting grid fit only.')

    results = []
    for Ns in grid_sizes:
        if not os.path.exists(gpath(Ns)):
            print(f'[plot-only] Ns={Ns}: no grid fit at {gpath(Ns)} — skipping')
            continue
        if use_final and not os.path.exists(fpath(Ns)):
            print(f'[plot-only] Ns={Ns}: final fit missing — skipping for consistency')
            continue

        gfit = np.load(gpath(Ns))
        n = min(len(trueFit_data), len(gfit))
        grid_space, _ = build_grid_space(stimulus, Ns)
        gc, gr2 = compute_metrics(trueFit_data[:n], gfit[:n])
        res = {
            'Ns': Ns,
            'n_grid_points': len(grid_space),
            'grid_prep_time': np.nan,
            'grid_fit_time': np.nan,
            'final_fit_time': np.nan,
            'grid': {'corr': gc, 'mean_r2': gr2,
                     'r2_by_bin': compute_r2_by_bin(gfit[:n, 1], bin_labels[:n], n_bins)},
            'final': None,
        }
        if use_final:
            ffit = np.load(fpath(Ns))
            m = min(len(trueFit_data), len(ffit))
            fc, fr2 = compute_metrics(trueFit_data[:m], ffit[:m])
            res['final'] = {'corr': fc, 'mean_r2': fr2,
                            'r2_by_bin': compute_r2_by_bin(ffit[:m, 1], bin_labels[:m], n_bins)}
        results.append(res)
        print(f'[plot-only] Ns={Ns}: loaded ({"grid+final" if use_final else "grid"})')

    return results, (not use_final)


def plot_accuracy_vs_ns(results, save_path, skip_final_fit):
    """One panel per correlated parameter: Pearson r vs Ns (grid & final)."""
    Ns_vals = [r['Ns'] for r in results]

    f, axs = plt.subplots(2, 3, figsize=(18, 10))
    axs = axs.flatten()
    for ax, (name, _) in zip(axs, CORR_PARAMS):
        grid_r = [r['grid']['corr'][name] for r in results]
        ax.plot(Ns_vals, grid_r, '-o', color='#00e5ff', linewidth=1.6,
                markersize=5, label='grid fit')
        if not skip_final_fit:
            final_r = [r['final']['corr'][name] for r in results]
            ax.plot(Ns_vals, final_r, '-s', color='#ff4081', linewidth=1.6,
                    markersize=5, label='final fit')
        ax.set_title(f'{name}: corr(fitted, ground truth) vs Ns')
        ax.set_xlabel('Grid size (Ns)')
        ax.set_ylabel('Pearson r')
        ax.grid(True, alpha=0.3)
        ax.legend(fontsize=9, framealpha=0.3)

    f.suptitle('Parameter recovery vs grid size', fontsize=15)
    plt.tight_layout()
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close(f)
    print(f'Accuracy-vs-Ns plot saved to {save_path}')


def plot_r2_vs_ns(results, save_path, skip_final_fit):
    """Mean fitted R² as a function of Ns (grid & final)."""
    Ns_vals = [r['Ns'] for r in results]

    f, ax = plt.subplots(figsize=(9, 6))
    grid_r2 = [r['grid']['mean_r2'] for r in results]
    ax.plot(Ns_vals, grid_r2, '-o', color='#00e5ff', linewidth=1.8,
            markersize=6, label='grid fit')
    if not skip_final_fit:
        final_r2 = [r['final']['mean_r2'] for r in results]
        ax.plot(Ns_vals, final_r2, '-s', color='#ff4081', linewidth=1.8,
                markersize=6, label='final fit')
    ax.set_title('Mean fitted R² vs grid size')
    ax.set_xlabel('Grid size (Ns)')
    ax.set_ylabel('Mean R²')
    ax.grid(True, alpha=0.3)
    ax.legend(fontsize=10, framealpha=0.3)

    plt.tight_layout()
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close(f)
    print(f'R²-vs-Ns plot saved to {save_path}')


def plot_r2_by_tfsp_bin(results, save_path, skip_final_fit, bin_medians, n_bins):
    """Mean R² vs Ns, one line per TFSP (SNR) decile, colored by TFSP.

    Left panel: grid fit. Right panel: final fit (omitted if skipped). Each line
    is a fixed set of voxels (binned by TFSP once), so the spread shows how SNR
    gates recoverable R² and how that interacts with grid density.
    """
    Ns_vals = [r['Ns'] for r in results]

    stages = [('grid', 'Grid-fit')]
    if not skip_final_fit:
        stages.append(('final', 'Final-fit'))

    f, axs = plt.subplots(1, len(stages), figsize=(9 * len(stages), 6),
                          squeeze=False)
    axs = axs[0]

    finite = np.isfinite(bin_medians)
    vmin = float(np.nanmin(bin_medians)) if finite.any() else 0.0
    vmax = float(np.nanmax(bin_medians)) if finite.any() else 1.0
    norm = Normalize(vmin=vmin, vmax=vmax if vmax > vmin else vmin + 1e-6)
    cmap = plt.cm.viridis

    for ax, (key, label) in zip(axs, stages):
        for b in range(n_bins):
            if not np.isfinite(bin_medians[b]):
                continue
            y = [r[key]['r2_by_bin'][b] for r in results]
            ax.plot(Ns_vals, y, '-o', markersize=4, linewidth=1.4,
                    color=cmap(norm(bin_medians[b])))
        ax.set_title(f'{label}: mean R² by TFSP decile vs Ns')
        ax.set_xlabel('Grid size (Ns)')
        ax.set_ylabel('Mean R²')
        ax.grid(True, alpha=0.3)

    sm = ScalarMappable(norm=norm, cmap=cmap)
    sm.set_array([])
    cbar = f.colorbar(sm, ax=list(axs), fraction=0.046, pad=0.04)
    cbar.set_label('TFSP (bin median, low → high SNR)')

    f.suptitle(f'R² by TFSP (SNR) decile vs grid size ({n_bins} bins)', fontsize=15)
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close(f)
    print(f'R²-by-TFSP-bin plot saved to {save_path}')


def plot_runtime_vs_ns(results, save_path, skip_final_fit):
    """Grid-fit (and final-fit) wall-clock time vs Ns, plus grid-point count."""
    Ns_vals = [r['Ns'] for r in results]

    f, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

    grid_t = [r['grid_fit_time'] for r in results]
    ax1.plot(Ns_vals, grid_t, '-o', color='#00e5ff', linewidth=1.8,
             markersize=6, label='grid fit')
    if not skip_final_fit:
        final_t = [r['final_fit_time'] for r in results]
        ax1.plot(Ns_vals, final_t, '-s', color='#ff4081', linewidth=1.8,
                 markersize=6, label='final fit')
    ax1.set_title('Fit runtime vs grid size')
    ax1.set_xlabel('Grid size (Ns)')
    ax1.set_ylabel('Wall-clock time (s)')
    ax1.grid(True, alpha=0.3)
    ax1.legend(fontsize=10, framealpha=0.3)

    n_points = [r['n_grid_points'] for r in results]
    ax2.plot(Ns_vals, n_points, '-o', color='#ffb300', linewidth=1.8, markersize=6)
    ax2.set_title('Constrained grid-point count vs grid size')
    ax2.set_xlabel('Grid size (Ns)')
    ax2.set_ylabel('# grid points')
    ax2.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close(f)
    print(f'Runtime-vs-Ns plot saved to {save_path}')


def save_metrics(results, save_path, skip_final_fit, bin_medians):
    """Persist the sweep metrics as a .npz for downstream inspection."""
    Ns_vals = np.array([r['Ns'] for r in results])
    payload = {
        'Ns': Ns_vals,
        'n_grid_points': np.array([r['n_grid_points'] for r in results]),
        'grid_prep_time': np.array([r['grid_prep_time'] for r in results]),
        'grid_fit_time': np.array([r['grid_fit_time'] for r in results]),
        'final_fit_time': np.array([r['final_fit_time'] for r in results]),
        'grid_mean_r2': np.array([r['grid']['mean_r2'] for r in results]),
        'n_grid_values': np.array(N_GRID_VALUES),
        # TFSP-binned R²: rows = Ns, cols = TFSP decile (bin_medians labels cols).
        'tfsp_bin_medians': np.asarray(bin_medians),
        'grid_r2_by_bin': np.array([r['grid']['r2_by_bin'] for r in results]),
    }
    for name, _ in CORR_PARAMS:
        payload[f'grid_corr_{name}'] = np.array([r['grid']['corr'][name] for r in results])
        if not skip_final_fit:
            payload[f'final_corr_{name}'] = np.array([r['final']['corr'][name] for r in results])
    if not skip_final_fit:
        payload['final_mean_r2'] = np.array([r['final']['mean_r2'] for r in results])
        payload['final_r2_by_bin'] = np.array([r['final']['r2_by_bin'] for r in results])

    np.savez(save_path, **payload)
    print(f'Sweep metrics saved to {save_path}')


# Ground truth is loaded once and shared across all Ns (module-level so the
# per-Ns fit helper can reference it without re-threading it through every call).
trueFit_data_global = None


def main():
    args = parse_args()
    codeStartTime = time.perf_counter()

    params = dict(DEFAULT_PARAMS)
    params['subjID'] = 'JC'
    p, _ = set_paths(params['subjID'], data_format='volumetric')

    # ── Logging setup ──────────────────────────────────────────────────────────
    log_dir = os.path.join(p['pRF_data'], 'Simulation', 'logs')
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    log_path = os.path.join(log_dir, f'S03_{timestamp}.log')
    logger = TeeLogger(log_path)
    sys.stdout = logger
    sys.stderr = logger
    # ───────────────────────────────────────────────────────────────────────────

    try:
        _run(args, codeStartTime, p, params)
    except Exception:
        traceback.print_exc()
        raise
    finally:
        print(f'\nLog saved to: {log_path}')
        logger.close()


def _run(args, codeStartTime, p, params):
    global trueFit_data_global
    set_dark_theme()

    # Load simulation data (shared across the whole sweep).
    print('Loading simulated data...')
    scan_data, trueFit_data = load_simulation_data(p, args.n_voxels)
    trueFit_data_global = trueFit_data
    nvoxs = scan_data.shape[0]

    print('=== Grid-size Sweep (S03) ===')
    print(f'Run started: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}')
    print(f'Mode:        {"plot-only (rebuild figures from saved fits)" if args.plot_only else "fit + plot"}')
    print(f'N voxels:    {nvoxs}')
    print(f'Grid sizes:  {args.grid_sizes}')
    print(f'n-grid:      {N_GRID_VALUES} ({len(N_GRID_VALUES)} values)')
    if not args.plot_only:
        print(f'GPU:         {"enabled" if args.use_gpu else "disabled"}')
        print(f'Prefetch:    {"disabled" if args.no_prefetch else "enabled (depth 1)"}')
        print(f'Final fit:   {"skipped" if args.skip_final_fit else "enabled"}')
        if not args.skip_final_fit:
            print(f'  n_iter:    {args.n_iter}')
            print(f'  lr:        {args.lr}')
            print(f'  sub_batch: {args.sub_batch if args.sub_batch is not None else "auto"}')
    print()

    # Detrend once.
    timeseries_data = remove_trend(scan_data, method='all')
    indices = [(0, 0, i) for i in range(nvoxs)]

    # Load stimulus once (identical across Ns).
    bar, _ = load_stimuli(p)
    bar = bar[:, :, 0:201]
    bar = np.flip(bar, axis=0)
    func_img = nib.load(p['pRF_ss5'])
    stimulus = VisualStimulus(
        bar.astype('int16'),
        params['viewingDistance'],
        params['screenWidth'],
        params['scaleFactor'],
        float(func_img.header['pixdim'][4]),
        params['dtype'],
    )

    # TFSP (SNR) per voxel, computed once from the detrended data (independent of
    # Ns). Voxels are binned by TFSP decile so R² can be tracked per SNR bin.
    print('Computing TFSP (SNR) per voxel and assigning TFSP bins...')
    tfsp, _, _, _ = compute_tfsp(timeseries_data, tr=params['tr_length'],
                                 sweep_period_s=TFSP_SWEEP_PERIOD_S)
    bin_labels, bin_medians = compute_tfsp_bins(tfsp, N_TFSP_BINS)

    # All S03 outputs live under dedicated S03 subfolders of the usual dirs.
    fit_dir = os.path.join(p['pRF_data'], 'Simulation', 'popeyeFit', 'S03')
    os.makedirs(fit_dir, exist_ok=True)
    fig_dir = os.path.join(p['pRF_data'], 'Simulation', 'figures', 'S03')
    os.makedirs(fig_dir, exist_ok=True)

    grid_sizes = list(args.grid_sizes)
    effective_skip = args.skip_final_fit

    if args.plot_only:
        # Rebuild results from previously saved fits — no fitting.
        results, effective_skip = build_results_from_saved(
            grid_sizes, fit_dir, stimulus, trueFit_data, args.skip_final_fit,
            bin_labels, N_TFSP_BINS)
        if not results:
            print('[plot-only] No saved fits found for the requested Ns — nothing to plot.')
            return
    else:
        # Sweep. The CPU grid-prediction of the next Ns is overlapped with the GPU
        # fit of the current Ns (prefetch depth 1), since they use disjoint resources
        # (process Pool vs GPU) and grid predictions are independent of the fit.
        nTRs = timeseries_data.shape[1]
        results = []

        def _prep(Ns):
            return prepare_gridpreds(Ns, stimulus, p, nTRs)

        if args.no_prefetch or len(grid_sizes) <= 1:
            for Ns in grid_sizes:
                grid_space, param_width, grid_preds, prep_time = _prep(Ns)
                results.append(
                    fit_from_preds(Ns, grid_space, param_width, grid_preds, prep_time,
                                   stimulus, timeseries_data, indices, nvoxs,
                                   args.use_gpu, args.skip_final_fit, fit_dir,
                                   bin_labels, N_TFSP_BINS,
                                   n_iter=args.n_iter, lr=args.lr, sub_batch=args.sub_batch)
                )
        else:
            print(f'\nPrefetch enabled: overlapping next-Ns grid prediction with '
                  f'current-Ns GPU fit (depth 1).')
            with ThreadPoolExecutor(max_workers=1) as ex:
                fut = ex.submit(_prep, grid_sizes[0])
                for i, Ns in enumerate(grid_sizes):
                    grid_space, param_width, grid_preds, prep_time = fut.result()
                    # Kick off the next Ns's CPU prediction before we occupy the GPU.
                    if i + 1 < len(grid_sizes):
                        fut = ex.submit(_prep, grid_sizes[i + 1])
                    results.append(
                        fit_from_preds(Ns, grid_space, param_width, grid_preds, prep_time,
                                       stimulus, timeseries_data, indices, nvoxs,
                                       args.use_gpu, args.skip_final_fit, fit_dir,
                                       bin_labels, N_TFSP_BINS,
                                       n_iter=args.n_iter, lr=args.lr, sub_batch=args.sub_batch)
                    )

    plot_accuracy_vs_ns(results, os.path.join(fig_dir, 'accuracy_vs_Ns.png'),
                        effective_skip)
    plot_r2_vs_ns(results, os.path.join(fig_dir, 'r2_vs_Ns.png'),
                  effective_skip)
    plot_r2_by_tfsp_bin(results, os.path.join(fig_dir, 'r2_by_tfsp_bin_vs_Ns.png'),
                        effective_skip, bin_medians, N_TFSP_BINS)
    if args.plot_only:
        print('[plot-only] Runtime figure skipped — per-Ns timing is not persisted.')
    else:
        plot_runtime_vs_ns(results, os.path.join(fig_dir, 'runtime_vs_Ns.png'),
                           effective_skip)
    save_metrics(results, os.path.join(fig_dir, 'sweep_metrics.npz'),
                 effective_skip, bin_medians)

    codeEndTime = time.perf_counter()
    print_time(codeStartTime, codeEndTime,
               'Total plot-only rebuild' if args.plot_only else 'Total grid-size sweep')


if __name__ == '__main__':
    main()
