"""
H03_fit_utils.py — Shared utility functions for the pRF fitting pipeline.

Contains:
    set_dark_theme()     — Apply consistent dark background style for matplotlib
    print_time()         — Formatted elapsed time printing
    remove_trend()       — Signal detrending and percent signal change
    constrain_grids()   — Eccentricity-based grid space pruning
    generate_bounds()    — Parameter bounds for optimization
    error_func()         — Objective function for scipy.optimize.minimize
"""

import warnings
import numpy as np
import matplotlib.pyplot as plt
from itertools import product
from scipy.signal import detrend
from scipy.stats import zscore,gamma
from scipy.integrate import trapezoid
from scipy.linalg import lstsq


### MISC ####

def set_dark_theme():
    """
    Apply a consistent dark theme for all matplotlib figures generated by the pipeline.
    Sets background to dark, high-contrast cyan/magenta/yellow accents, subtle grids.
    """
    plt.style.use('dark_background')
    plt.rcParams.update({
        'figure.facecolor': '#121212',
        'axes.facecolor': '#1e1e1e',
        'axes.edgecolor': '#444444',
        'axes.labelcolor': '#e0e0e0',
        'xtick.color': '#cccccc',
        'ytick.color': '#cccccc',
        'grid.color': '#333333',
        'grid.linestyle': '--',
        'grid.alpha': 0.5,
        'figure.titlesize': 14,
        'axes.titlesize': 12,
        'text.color': '#ffffff',
        'savefig.facecolor': '#121212',
        'savefig.edgecolor': 'none',
    })


def print_time(st_time, end_time, process_name):
    """Print elapsed time in a human-readable format."""
    duration = end_time - st_time
    if duration < 60:
        print(f'{process_name} took {round(duration, 2)} seconds')
    elif duration < 3600:
        print(f'{process_name} took {round(duration/60)} minutes '
              f'and {round(duration%60)} seconds')
    else:
        print(f'{process_name} took {round(duration//3600)} hours, '
              f'{round((duration%3600)//60)} minutes '
              f'and {round(duration%60)} seconds')


#helper function to convert a 2D set of fit results from grid or final fit into
#a volume or surface with indices matched to source voxels/vertices.
def results_to_img(fit_img,results,indices):

    indices = np.asarray(indices)
    if indices.ndim == 2:
        fit_img[indices[:, 0], indices[:, 1], indices[:, 2], :] = results  # volumetric 3D index
    else:
        fit_img[indices, :] = results  # surface 1D index

    return fit_img


### BOLD PREPROCESSING ###

def make_trends(n_frames, n_dct, verbose=False):
    """
    Create cosine trends for detrending fMRI data.
    Adapted from Vista rmMakeTrends.m.

    Parameters
    ----------
    n_frames : int
        Number of frames in the scan.
    n_dct : int
        Maximum DCT order. The number of trends is 2 * n_dct + 1.
    verbose : bool, default=False
        Print the number of generated trends.

    Returns
    -------
    t : numpy.ndarray, shape (n_frames, 2 * n_dct + 1)
        Cosine trend matrix.
    nt : int
        Number of trends.
    dcid : int
        Zero-based column index of the DC component.
    """
    n_frames = int(n_frames)
    n_dct = int(n_dct)

    if n_frames < 1:
        raise ValueError("n_frames must be positive")
    if n_dct < 0:
        raise ValueError("n_dct must be nonnegative")

    # MATLAB linspace(0, 2*pi, n_frames), including the endpoint.
    tc = np.linspace(0.0, 2.0 * np.pi, n_frames)

    # Equivalent to MATLAB's 0:0.5:nDCT.
    frequencies = np.arange(0.0, n_dct + 0.5, 0.5)

    # Outer product: one column per cosine frequency.
    t = np.cos(tc[:, None] * frequencies[None, :])

    nt = t.shape[1]

    # # MATLAB's dcid would be 1; Python uses zero-based indexing.
    # dcid = 0

    if verbose:
        print(f"Removing {nt} trends from combined data.")

    return t #t, nt, dcid

def detrend_vista(signal, n_dct=1):
    """
    Detrend fMRI signal using cosine trends, similar to Vista's rmMakeTrends.

    Parameters
    ----------
    signal : numpy.ndarray, shape (n_voxels, n_timepoints)
        Input fMRI signal.
    n_dct (int, default=1):
        Maximum DCT order for detrending.

    Returns
    -------
    detrended_signal : numpy.ndarray, shape (n_voxels, n_timepoints)
        Detrended fMRI signal.
    """

    #compute trends
    n_frames = signal.shape[1]
    trends = make_trends(n_frames, n_dct)

    # Fit trends to the signal using least squares and remove them
    betas, *_ = lstsq(trends, signal.T)
    detrended_signal = signal - (trends @ betas).T
   
    return detrended_signal


def preprocess_signal(signal, detrend_method, **kwargs):
    """
    Detrend and normalize (z-score) fMRI signal.
    Note: z-scoring is required for the model fitting to work properly, so other normalization 
    methods are no longer supported.

    Parameters
    ----------
    signal : ndarray
        Input signal array. Last axis is time.
    detrend_method : str
        'detrend'                — scipy.signal.detrend (linear detrending by default)
        'detrend_vista'           — Detrending using cosine trends (Vista-style)
        None or 'none'             — No detrending
    kwargs : additional keyword arguments to pass to the detrending functions (if needed).

    Returns
    -------
    ndarray
        Processed signal.
    """
    if detrend_method == 'detrend':
        #signal_mean = np.mean(signal, axis=-1)[..., None]
        signal_detrend = detrend(signal, axis=-1, **kwargs) #+ signal_mean``
    elif detrend_method == 'detrend_vista':
        signal_detrend = detrend_vista(signal, **kwargs)
    elif detrend_method is None or detrend_method == 'none':
        signal_detrend = signal
    else:
        raise ValueError(f"Unknown detrend method: '{detrend_method}'")

    # Z-score normalization
    signal_normalized = zscore(signal_detrend, axis=-1)

    return signal_normalized


### GRID CREATION ###

#adapted from vista rmSpaceSigmas.m
def linlogspace(start, stop, num, border, pctlin, reflect=False):
    """
    Generate spacing with linear section up to border, then log spacing after.
    
    Adapted from mrVista's rmSpaceSigmas.m. Linear spacing from `start` to 
    `border`, then log spacing from `border` to `stop`.
    
    Parameters
    ----------
    start : float
        Minimum value (minRF).
    stop : float
        Maximum value (maxRF).
    num : int
        Total number of points to generate.
    border : float
        Transition point between linear and log spacing.
    pctlin : float
        Percentage of points in the linear segment.
    reflect : bool
        Reflect the values about zero (i.e. values go from -stop:stop).
        Note: Will not give you the N you request w/ odd values of N or start==0, but you can do it if you want.
    
    Returns
    -------
    ndarray
        Spaced values from start to stop.
    """

    if reflect:
        assert (start>=0) and (stop>=0)
        if start==0:
            warnings.warn('Will return N-1 points if start==0 and reflect=True')
        if np.mod(num,2) == 1:
            warnings.warn('Will return N-1 points if N is odd and reflect=True.')
        num = num//2
    
    if stop <= border:
        # All linear if stop is within border
        return np.linspace(start, stop, num)

    # If border very close to stop, ignore pctlin
    r = border / stop
    r = max(r, pctlin)
    # Number of points in each section
    h1 = int(np.floor(num * r))       # linear points
    h2 = int(np.ceil(num * np.round(1 - r,decimals=3)))  # log points (round to handle floating point slop)
    assert h1+h2 == num
    
    # Linear section: start to border (exclude last point to avoid duplication)
    tmp = np.linspace(start, border, h1 + 1)
    s_lin = tmp[:-1]
    
    # Log section: border to stop
    s_log = np.geomspace(border, stop, h2)
    
    # Concatenate and return
    out = np.concatenate((s_lin, s_log))
    if not reflect:
        return out
    else:
        return np.sort(np.unique(np.concatenate((-out, out))))   

def _grid_axis_from_params(params):
    space = params['space']
    p = params.copy()
    del p['space']
    if space == 'lin':
        return np.linspace(**p)
    elif space=='log':
        return np.geomspace(**p)
    elif space=='linlog':
        return linlogspace(**p)
    else:
        raise ValueError('Unknkown grid spacing specified.')

def _set_param_minmax(grid_params,param, min_value=None, max_value=None):
    if min_value is not None:
        grid_params[param].update({'start':min_value})
    if max_value is not None:
        grid_params[param].update({'stop':max_value})

def _set_param_gridN(grid_params,N,param_list=('x','y','s')):
    for p in param_list:
        grid_params[p].update({'num': N})

def generate_grids(grid_params,constraint_func=None,*args):
    if isinstance(grid_params,dict):
        params = list(grid_params.values())
    else:
        params = grid_params.copy()

    grid_space_orig = np.array(list(product(*[_grid_axis_from_params(x) for x in params])), dtype=float)
    grid_space_orig = np.round(grid_space_orig,4)

    return grid_space_orig if constraint_func is None else constraint_func(grid_space_orig,*args)

    
def constrain_grids(grid_space_orig, stimulus):
    """
    Remove grid points that fall outside the stimulus field of view.

    Applies two eccentricity constraints:
        1. sqrt(x² + y²) < 2 * max_eccentricity
        2. sqrt(x² + y²) < max_eccentricity + 2 * sigma

    Parameters
    ----------
    grid_space_orig : list of tuple or ndarray
        Grid points as (x, y, sigma, n) tuples.
    stimulus : VisualStimulus
        Popeye stimulus object.

    Returns
    -------
    list of list
        Constrained grid points.
    """
    grid_space_orig = np.array(grid_space_orig)
    x, y, s = grid_space_orig[:, 0], grid_space_orig[:, 1], grid_space_orig[:, 2]
    distances = np.sqrt(x**2 + y**2)

    max_dist1 = 2 * stimulus.deg_x.max()
    max_dist2 = stimulus.deg_x.max() + 2 * s

    mask = (distances < max_dist1) & (distances < max_dist2)
    grid_space = grid_space_orig[mask]
    return grid_space #.tolist()


def generate_bounds(init_estim, param_width):
    """
    Generate parameter bounds for optimization based on grid estimate.

    Parameters
    ----------
    init_estim : array-like
        Initial estimate (9-element: theta, r2, rho, sigma, n, x, y, beta, baseline).
    param_width : list
        Search width for [x, y, sigma, n].

    Returns
    -------
    tuple of tuple
        Bounds for (x, y, sigma, n).
    """
    x_estim = init_estim[5]
    y_estim = init_estim[6]
    sigma_estim = init_estim[3]
    n_estim = init_estim[4]

    x_bounds = (x_estim - param_width[0], x_estim + param_width[0])
    y_bounds = (y_estim - param_width[1], y_estim + param_width[1])
    sigma_bounds = (sigma_estim - param_width[2], sigma_estim + param_width[2])
    n_bounds = (n_estim - param_width[3], n_estim + param_width[3])

    return (x_bounds, y_bounds, sigma_bounds, n_bounds)


### HRF models ###

def double_gamma_hrf(delay, tr, fptr=1.0, integrator=trapezoid,dtype='float32'):

    r"""The double gamma hemodynamic reponse function (HRF).
    The user specifies only the delay of the peak and undershoot.
    The delay shifts the peak and undershoot by a variable number of
    seconds. The other parameters are hardcoded. The HRF delay is
    modeled for each voxel independently. The form of the HRF and the
    hardcoded values are based on previous work [1]_.

    Parameters
    ----------
    delay : float
        The delay of the HRF peak and undershoot.

    tr : float
        The length of the repetition time in seconds.

    fptr : float
        The number of stimulus frames per reptition time.  For a
        60 Hz projector and with a 1 s repetition time, the fptr
        would be equal to 60.  It is possible that you will bin all
        the frames in a single TR, in which case fptr equals 1.

    integrator : callable
        The integration function for normalizing the units of the HRF
        so that the area under the curve is the same for differently
        delayed HRFs.  Set integrator to None to turn off normalization.

    Returns
    -------
    hrf : ndarray
        The hemodynamic response function to convolve with the stimulus
        timeseries.

    Reference
    ----------
    .. [1] Glover, GH (1999) Deconvolution of impulse response in event related
    BOLD fMRI. NeuroImage 9, 416-429.

    """
    from scipy.special import gamma
    
    # add delay to the peak and undershoot params (alpha 1 and 2)
    alpha_1 = float(5 + delay)
    beta_1 = 1.0
    c = 0.1
    alpha_2 = float(15 + delay)
    beta_2 = 1.0
    
    t = np.arange(0,32,tr)
    
    hrf = ( ( ( t ** (alpha_1) * beta_1 ** alpha_1 * np.exp( -beta_1 * t )) /gamma( alpha_1 )) - c *
            ( ( t ** (alpha_2) * beta_2 ** alpha_2 * np.exp( -beta_2 * t )) /gamma( alpha_2 )) )
            
    if integrator: # pragma: no cover
        hrf /= integrator(hrf)
        
    return hrf.astype(dtype)

def _gamma_difference_hrf(tr, oversampling=1, time_length=32., onset=0.,
                         delay=5, undershoot=15., dispersion=1.,
                         u_dispersion=1., ratio=0.167):
    """ Compute an hrf as the difference of two gamma functions
    Parameters
    ----------
    tr: float, scan repeat time, in seconds
    oversampling: int, temporal oversampling factor, optional
    time_length: float, hrf kernel length, in seconds
    onset: float, onset of the hrf
    Returns
    -------
    hrf: array of shape(length / tr * oversampling, float),
         hrf sampling on the oversampled time grid
    """
    dt = tr / oversampling
    time_stamps = np.linspace(0, time_length, int(float(time_length) / dt))
    time_stamps -= onset / dt
    hrf = gamma.pdf(time_stamps, delay / dispersion, dt / dispersion) - \
        ratio * gamma.pdf(
        time_stamps, undershoot / u_dispersion, dt / u_dispersion)
    hrf /= trapezoid(hrf)
    return hrf

def spm_hrf(delay, tr, oversampling=1, time_length=32., onset=0.):
    """ Implementation of the SPM hrf model
    Parameters
    ----------
    tr: float, scan repeat time, in seconds
    oversampling: int, temporal oversampling factor, optional
    time_length: float, hrf kernel length, in seconds
    onset: float, onset of the response
    Returns
    -------
    hrf: array of shape(length / tr * oversampling, float),
         hrf sampling on the oversampled time grid
    """
    return _gamma_difference_hrf(tr, oversampling, time_length, onset, delay=5+delay, undershoot=15+delay,)


def glover_hrf(delay, tr, oversampling=1, time_length=32., onset=0.):
    """ Implementation of the Glover hrf model
    Parameters
    ----------
    tr: float, scan repeat time, in seconds
    oversampling: int, temporal oversampling factor, optional
    time_length: float, hrf kernel length, in seconds
    onset: float, onset of the response
    Returns
    -------
    hrf: array of shape(length / tr * oversampling, float),
         hrf sampling on the oversampled time grid
    """
    return _gamma_difference_hrf(tr, oversampling, time_length, onset,
                                delay=5+delay, undershoot=15+delay, dispersion=.9,
                                u_dispersion=.9, ratio=.35)


def hrf_two_gammas(tr, params=None, integrator=trapezoid, dtype='float32'):
    r"""SPM-style two-gamma HRF, as in Glover, NeuroImage 9:416-429.

    Ported/adapted from vistasoft's ``rmHrfTwogammas.m``.

    Parameters
    ----------
    tr : float
        The length of the repetition time in seconds.

    params : sequence of 5 floats, optional
        (peak1, fwhm1, peak2, fwhm2, dip). Defaults to
        (5.4, 5.2, 10.8, 7.35, 0.35).

    Returns
    -------
    h : ndarray
        h = gamma1 - dip * gamma2, unnormalized (matching the original,
        which leaves its own `h./sum(h)` normalization commented out).
    """
    t = np.arange(0,32,tr)

    if params is None:
        params = (5.4, 5.2, 10.8, 7.35, 0.35)
    peak1, fwhm1, peak2, fwhm2, dip = params

    if peak1 == 0 or fwhm1 == 0:
        raise ValueError(f"rm_hrf_two_gammas: zero params: {params}")

    alpha1 = peak1 ** 2 / fwhm1 ** 2 * 8 * np.log(2)
    beta1 = fwhm1 ** 2 / peak1 / 8 / np.log(2)
    gamma1 = (t / peak1) ** alpha1 * np.exp(-(t - peak1) / beta1)

    if peak2 > 0 and fwhm2 > 0:
        alpha2 = peak2 ** 2 / fwhm2 ** 2 * 8 * np.log(2)
        beta2 = fwhm2 ** 2 / peak2 / 8 / np.log(2)
        gamma2 = (t / peak2) ** alpha2 * np.exp(-(t - peak2) / beta2)
    else:
        abs_diff = np.abs(t - peak2)
        gamma2 = (abs_diff == abs_diff.min()).astype(float)

    hrf = gamma1 - dip * gamma2

    if integrator: # pragma: no cover
        hrf /= integrator(hrf)

    return hrf.astype(dtype)


